module Evergreen.V108.Sound exposing (..)


type Sound
    = PopSound
    | CrackleSound
    | TrainWhistleSound
    | ChugaChuga
    | EraseSound
    | PageTurnSound
    | WhooshSound
    | ErrorSound
    | KnockKnockSound
    | OldManSound
    | MmhmmSound
    | NuhHuhSound
    | HelloSound
    | Hello2Sound
    | TeleportSound
    | Music0
    | Music1
    | Music2
    | Ambience0
    | Moo0
    | Moo1
    | Moo2
    | Moo3
    | Moo4
    | Moo5
    | Moo6
    | RailToggleSound
    | Meow
    | TrainCrash
    | Sheep0
    | Sheep1
    | Hamster0
    | Hamster1
    | Hamster2
    | LightSwitch
