module Evergreen.Migrate.V100 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import AssocSet
import Dict
import Evergreen.V100.AdminPage
import Evergreen.V100.Animal
import Evergreen.V100.Audio
import Evergreen.V100.Bounds
import Evergreen.V100.Change
import Evergreen.V100.Color
import Evergreen.V100.Coord
import Evergreen.V100.Cursor
import Evergreen.V100.DisplayName
import Evergreen.V100.EmailAddress
import Evergreen.V100.Geometry.Types
import Evergreen.V100.Grid
import Evergreen.V100.GridCell
import Evergreen.V100.Id
import Evergreen.V100.IdDict
import Evergreen.V100.Keyboard
import Evergreen.V100.LocalGrid
import Evergreen.V100.LocalModel
import Evergreen.V100.MailEditor
import Evergreen.V100.Point2d
import Evergreen.V100.Route
import Evergreen.V100.Sound
import Evergreen.V100.TextInput
import Evergreen.V100.Tile
import Evergreen.V100.TimeOfDay
import Evergreen.V100.Tool
import Evergreen.V100.Train
import Evergreen.V100.Types
import Evergreen.V100.Ui
import Evergreen.V100.Units
import Evergreen.V100.Untrusted
import Evergreen.V100.User
import Evergreen.V99.AdminPage
import Evergreen.V99.Animal
import Evergreen.V99.Audio
import Evergreen.V99.Bounds
import Evergreen.V99.Change
import Evergreen.V99.Color
import Evergreen.V99.Coord
import Evergreen.V99.Cursor
import Evergreen.V99.DisplayName
import Evergreen.V99.EmailAddress
import Evergreen.V99.Geometry.Types
import Evergreen.V99.Grid
import Evergreen.V99.GridCell
import Evergreen.V99.Id
import Evergreen.V99.IdDict
import Evergreen.V99.Keyboard
import Evergreen.V99.LocalGrid
import Evergreen.V99.LocalModel
import Evergreen.V99.MailEditor
import Evergreen.V99.Point2d
import Evergreen.V99.Route
import Evergreen.V99.Sound
import Evergreen.V99.TextInput
import Evergreen.V99.Tile
import Evergreen.V99.TimeOfDay
import Evergreen.V99.Tool
import Evergreen.V99.Train
import Evergreen.V99.Types
import Evergreen.V99.Ui
import Evergreen.V99.Units
import Evergreen.V99.Untrusted
import Evergreen.V99.User
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Maybe
import Quantity


frontendModel : Evergreen.V99.Types.FrontendModel -> ModelMigration Evergreen.V100.Types.FrontendModel Evergreen.V100.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V99.Types.BackendModel -> ModelMigration Evergreen.V100.Types.BackendModel Evergreen.V100.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V99.Types.FrontendMsg -> MsgMigration Evergreen.V100.Types.FrontendMsg Evergreen.V100.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V99.Types.ToBackend -> MsgMigration Evergreen.V100.Types.ToBackend Evergreen.V100.Types.BackendMsg
toBackend old =
    MsgOldValueIgnored


backendMsg : Evergreen.V99.Types.BackendMsg -> MsgMigration Evergreen.V100.Types.BackendMsg Evergreen.V100.Types.BackendMsg
backendMsg old =
    MsgOldValueIgnored


toFrontend : Evergreen.V99.Types.ToFrontend -> MsgMigration Evergreen.V100.Types.ToFrontend Evergreen.V100.Types.FrontendMsg
toFrontend old =
    MsgOldValueIgnored
