module Evergreen.Migrate.V116 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import AssocSet
import Dict
import Evergreen.V115.Animal
import Evergreen.V115.Bounds
import Evergreen.V115.Change
import Evergreen.V115.Color
import Evergreen.V115.Coord
import Evergreen.V115.Cursor
import Evergreen.V115.DisplayName
import Evergreen.V115.EmailAddress
import Evergreen.V115.Geometry.Types
import Evergreen.V115.Grid
import Evergreen.V115.GridCell
import Evergreen.V115.Hyperlink
import Evergreen.V115.Id
import Evergreen.V115.IdDict
import Evergreen.V115.MailEditor
import Evergreen.V115.PersonName
import Evergreen.V115.Point2d
import Evergreen.V115.Postmark
import Evergreen.V115.Route
import Evergreen.V115.TextInput
import Evergreen.V115.TextInputMultiline
import Evergreen.V115.Tile
import Evergreen.V115.TileCountBot
import Evergreen.V115.TimeOfDay
import Evergreen.V115.Train
import Evergreen.V115.Types
import Evergreen.V115.Ui
import Evergreen.V115.Units
import Evergreen.V116.Animal
import Evergreen.V116.Bounds
import Evergreen.V116.Change
import Evergreen.V116.Color
import Evergreen.V116.Coord
import Evergreen.V116.Cursor
import Evergreen.V116.DisplayName
import Evergreen.V116.EmailAddress
import Evergreen.V116.Geometry.Types
import Evergreen.V116.Grid
import Evergreen.V116.GridCell
import Evergreen.V116.Hyperlink
import Evergreen.V116.Id
import Evergreen.V116.IdDict
import Evergreen.V116.MailEditor
import Evergreen.V116.PersonName
import Evergreen.V116.Point2d
import Evergreen.V116.Postmark
import Evergreen.V116.Route
import Evergreen.V116.TextInput
import Evergreen.V116.TextInputMultiline
import Evergreen.V116.Tile
import Evergreen.V116.TileCountBot
import Evergreen.V116.TimeOfDay
import Evergreen.V116.Train
import Evergreen.V116.Types
import Evergreen.V116.Ui
import Evergreen.V116.Units
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Maybe
import Quantity
import Set


frontendModel : Evergreen.V115.Types.FrontendModel -> ModelMigration Evergreen.V116.Types.FrontendModel Evergreen.V116.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V115.Types.BackendModel -> ModelMigration Evergreen.V116.Types.BackendModel Evergreen.V116.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V115.Types.FrontendMsg -> MsgMigration Evergreen.V116.Types.FrontendMsg Evergreen.V116.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V115.Types.ToBackend -> MsgMigration Evergreen.V116.Types.ToBackend Evergreen.V116.Types.BackendMsg
toBackend old =
    MsgOldValueIgnored


backendMsg : Evergreen.V115.Types.BackendMsg -> MsgMigration Evergreen.V116.Types.BackendMsg Evergreen.V116.Types.BackendMsg
backendMsg old =
    MsgOldValueIgnored


toFrontend : Evergreen.V115.Types.ToFrontend -> MsgMigration Evergreen.V116.Types.ToFrontend Evergreen.V116.Types.FrontendMsg
toFrontend old =
    MsgOldValueIgnored


migrate_Types_BackendModel : Evergreen.V115.Types.BackendModel -> Evergreen.V116.Types.BackendModel
migrate_Types_BackendModel old =
    { grid = old.grid |> migrate_Grid_Grid migrate_GridCell_BackendHistory
    , userSessions =
        old.userSessions
            |> Dict.map
                (\_ ->
                    \rec ->
                        { clientIds = rec.clientIds |> migrate_AssocList_Dict identity (List.map (migrate_Bounds_Bounds migrate_Units_CellUnit))
                        , userId = rec.userId |> Maybe.map (migrate_Id_Id migrate_Id_UserId)
                        }
                )
    , users = old.users |> migrate_IdDict_IdDict migrate_Id_UserId migrate_Types_BackendUserData
    , secretLinkCounter = old.secretLinkCounter
    , errors = old.errors |> List.map (Tuple.mapSecond migrate_Types_BackendError)
    , trains = old.trains |> migrate_IdDict_IdDict migrate_Id_TrainId migrate_Train_Train
    , animals = old.animals |> migrate_IdDict_IdDict migrate_Id_AnimalId migrate_Animal_Animal
    , people = old.people |> migrate_IdDict_IdDict migrate_Id_PersonId migrate_Types_Person
    , lastWorldUpdateTrains = old.lastWorldUpdateTrains |> migrate_IdDict_IdDict migrate_Id_TrainId migrate_Train_Train
    , lastWorldUpdate = old.lastWorldUpdate
    , mail = old.mail |> migrate_IdDict_IdDict migrate_Id_MailId migrate_MailEditor_BackendMail
    , pendingLoginTokens =
        old.pendingLoginTokens
            |> migrate_AssocList_Dict (migrate_Id_SecretId migrate_Route_LoginToken)
                (\rec ->
                    { requestTime = rec.requestTime
                    , userId = rec.userId |> migrate_Id_Id migrate_Id_UserId
                    }
                )
    , pendingOneTimePasswords =
        old.pendingOneTimePasswords
            |> migrate_AssocList_Dict identity
                (\rec ->
                    { requestTime = rec.requestTime
                    , userId = rec.userId |> migrate_Id_Id migrate_Id_UserId
                    , loginAttempts = rec.loginAttempts
                    , oneTimePassword = rec.oneTimePassword |> migrate_Id_SecretId migrate_Id_OneTimePasswordId
                    }
                )
    , invites = old.invites |> migrate_AssocList_Dict (migrate_Id_SecretId migrate_Route_InviteToken) migrate_Types_Invite
    , lastCacheRegeneration = old.lastCacheRegeneration
    , reported = old.reported |> migrate_IdDict_IdDict migrate_Id_UserId (migrate_List_Nonempty_Nonempty migrate_Change_BackendReport)
    , isGridReadOnly = old.isGridReadOnly
    , trainsAndAnimalsDisabled = old.trainsAndAnimalsDisabled |> migrate_Change_AreTrainsAndAnimalsDisabled
    , lastReportEmailToAdmin = old.lastReportEmailToAdmin
    , worldUpdateDurations = old.worldUpdateDurations
    , tileCountBot = old.tileCountBot |> Maybe.map migrate_TileCountBot_Model
    }


migrate_Animal_Animal : Evergreen.V115.Animal.Animal -> Evergreen.V116.Animal.Animal
migrate_Animal_Animal old =
    { position = old.position |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit
    , startTime = old.startTime
    , endPosition = old.endPosition |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit
    , animalType = old.animalType |> migrate_Animal_AnimalType
    }


migrate_Animal_AnimalType : Evergreen.V115.Animal.AnimalType -> Evergreen.V116.Animal.AnimalType
migrate_Animal_AnimalType old =
    case old of
        Evergreen.V115.Animal.Cow ->
            Evergreen.V116.Animal.Cow

        Evergreen.V115.Animal.Hamster ->
            Evergreen.V116.Animal.Hamster

        Evergreen.V115.Animal.Sheep ->
            Evergreen.V116.Animal.Sheep


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_AssocSet_Set : (a_old -> a_new) -> AssocSet.Set a_old -> AssocSet.Set a_new
migrate_AssocSet_Set migrate_a old =
    old |> AssocSet.map migrate_a


migrate_Bounds_Bounds : (unit_old -> unit_new) -> Evergreen.V115.Bounds.Bounds unit_old -> Evergreen.V116.Bounds.Bounds unit_new
migrate_Bounds_Bounds migrate_unit old =
    case old of
        Evergreen.V115.Bounds.Bounds p0 ->
            Evergreen.V116.Bounds.Bounds
                { min = p0.min |> migrate_Coord_Coord migrate_unit
                , max = p0.max |> migrate_Coord_Coord migrate_unit
                }


migrate_Change_AreTrainsAndAnimalsDisabled : Evergreen.V115.Change.AreTrainsAndAnimalsDisabled -> Evergreen.V116.Change.AreTrainsAndAnimalsDisabled
migrate_Change_AreTrainsAndAnimalsDisabled old =
    case old of
        Evergreen.V115.Change.TrainsAndAnimalsDisabled ->
            Evergreen.V116.Change.TrainsAndAnimalsDisabled

        Evergreen.V115.Change.TrainsAndAnimalsEnabled ->
            Evergreen.V116.Change.TrainsAndAnimalsEnabled


migrate_Change_BackendReport : Evergreen.V115.Change.BackendReport -> Evergreen.V116.Change.BackendReport
migrate_Change_BackendReport old =
    { reportedUser = old.reportedUser |> migrate_Id_Id migrate_Id_UserId
    , position = old.position |> migrate_Coord_Coord migrate_Units_WorldUnit
    , reportedAt = old.reportedAt
    }


migrate_Change_TileHotkey : Evergreen.V115.Change.TileHotkey -> Evergreen.V116.Change.TileHotkey
migrate_Change_TileHotkey old =
    case old of
        Evergreen.V115.Change.Hotkey0 ->
            Evergreen.V116.Change.Hotkey0

        Evergreen.V115.Change.Hotkey1 ->
            Evergreen.V116.Change.Hotkey1

        Evergreen.V115.Change.Hotkey2 ->
            Evergreen.V116.Change.Hotkey2

        Evergreen.V115.Change.Hotkey3 ->
            Evergreen.V116.Change.Hotkey3

        Evergreen.V115.Change.Hotkey4 ->
            Evergreen.V116.Change.Hotkey4

        Evergreen.V115.Change.Hotkey5 ->
            Evergreen.V116.Change.Hotkey5

        Evergreen.V115.Change.Hotkey6 ->
            Evergreen.V116.Change.Hotkey6

        Evergreen.V115.Change.Hotkey7 ->
            Evergreen.V116.Change.Hotkey7

        Evergreen.V115.Change.Hotkey8 ->
            Evergreen.V116.Change.Hotkey8

        Evergreen.V115.Change.Hotkey9 ->
            Evergreen.V116.Change.Hotkey9


migrate_Color_Color : Evergreen.V115.Color.Color -> Evergreen.V116.Color.Color
migrate_Color_Color old =
    case old of
        Evergreen.V115.Color.Color p0 ->
            Evergreen.V116.Color.Color p0


migrate_Color_Colors : Evergreen.V115.Color.Colors -> Evergreen.V116.Color.Colors
migrate_Color_Colors old =
    { primaryColor = old.primaryColor |> migrate_Color_Color
    , secondaryColor = old.secondaryColor |> migrate_Color_Color
    }


migrate_Coord_Coord : (units_old -> units_new) -> Evergreen.V115.Coord.Coord units_old -> Evergreen.V116.Coord.Coord units_new
migrate_Coord_Coord migrate_units old =
    old |> Tuple.mapBoth migrate_Quantity_Quantity migrate_Quantity_Quantity


migrate_Cursor_Cursor : Evergreen.V115.Cursor.Cursor -> Evergreen.V116.Cursor.Cursor
migrate_Cursor_Cursor old =
    { position = old.position |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit
    , holdingCow =
        old.holdingCow
            |> Maybe.map
                (\rec ->
                    { cowId = rec.cowId |> migrate_Id_Id migrate_Id_AnimalId
                    , pickupTime = rec.pickupTime
                    }
                )
    , currentTool = old.currentTool |> migrate_Cursor_OtherUsersTool
    }


migrate_Cursor_OtherUsersTool : Evergreen.V115.Cursor.OtherUsersTool -> Evergreen.V116.Cursor.OtherUsersTool
migrate_Cursor_OtherUsersTool old =
    case old of
        Evergreen.V115.Cursor.HandTool ->
            Evergreen.V116.Cursor.HandTool

        Evergreen.V115.Cursor.TilePlacerTool ->
            Evergreen.V116.Cursor.TilePlacerTool

        Evergreen.V115.Cursor.TilePickerTool ->
            Evergreen.V116.Cursor.TilePickerTool

        Evergreen.V115.Cursor.EraserTool ->
            Evergreen.V116.Cursor.EraserTool

        Evergreen.V115.Cursor.TextTool p0 ->
            Evergreen.V116.Cursor.TextTool
                (p0
                    |> Maybe.map
                        (\rec1 ->
                            { cursorPosition = rec1.cursorPosition |> migrate_Coord_Coord migrate_Units_WorldUnit
                            }
                        )
                )

        Evergreen.V115.Cursor.ReportTool ->
            Evergreen.V116.Cursor.ReportTool


migrate_DisplayName_DisplayName : Evergreen.V115.DisplayName.DisplayName -> Evergreen.V116.DisplayName.DisplayName
migrate_DisplayName_DisplayName old =
    case old of
        Evergreen.V115.DisplayName.DisplayName p0 ->
            Evergreen.V116.DisplayName.DisplayName p0


migrate_EmailAddress_EmailAddress : Evergreen.V115.EmailAddress.EmailAddress -> Evergreen.V116.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V115.EmailAddress.EmailAddress p0 ->
            Evergreen.V116.EmailAddress.EmailAddress p0


migrate_Geometry_Types_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V115.Geometry.Types.Point2d units_old coordinates_old -> Evergreen.V116.Geometry.Types.Point2d units_new coordinates_new
migrate_Geometry_Types_Point2d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V115.Geometry.Types.Point2d p0 ->
            Evergreen.V116.Geometry.Types.Point2d p0


migrate_GridCell_BackendHistory : Evergreen.V115.GridCell.BackendHistory -> Evergreen.V116.GridCell.BackendHistory
migrate_GridCell_BackendHistory old =
    case old of
        Evergreen.V115.GridCell.BackendDecoded p0 ->
            Evergreen.V116.GridCell.BackendDecoded (p0 |> List.map migrate_GridCell_Value)

        Evergreen.V115.GridCell.BackendEncodedAndDecoded p0 p1 ->
            Evergreen.V116.GridCell.BackendEncodedAndDecoded p0 (p1 |> List.map migrate_GridCell_Value)


migrate_GridCell_Cell : (a_old -> a_new) -> Evergreen.V115.GridCell.Cell a_old -> Evergreen.V116.GridCell.Cell a_new
migrate_GridCell_Cell migrate_a old =
    case old of
        Evergreen.V115.GridCell.Cell p0 ->
            Evergreen.V116.GridCell.Cell
                { history = p0.history |> migrate_a
                , undoPoint = p0.undoPoint |> migrate_IdDict_IdDict migrate_Id_UserId identity
                , cache = p0.cache |> List.map migrate_GridCell_Value
                , railSplitToggled = p0.railSplitToggled |> migrate_AssocSet_Set (migrate_Coord_Coord migrate_Units_CellLocalUnit)
                , mapCache = p0.mapCache
                }


migrate_GridCell_Value : Evergreen.V115.GridCell.Value -> Evergreen.V116.GridCell.Value
migrate_GridCell_Value old =
    { userId = old.userId |> migrate_Id_Id migrate_Id_UserId
    , position = old.position |> migrate_Coord_Coord migrate_Units_CellLocalUnit
    , tile = old.tile |> migrate_Tile_Tile
    , colors = old.colors |> migrate_Color_Colors
    , time = old.time
    }


migrate_Grid_Grid : (a_old -> a_new) -> Evergreen.V115.Grid.Grid a_old -> Evergreen.V116.Grid.Grid a_new
migrate_Grid_Grid migrate_a old =
    case old of
        Evergreen.V115.Grid.Grid p0 ->
            Evergreen.V116.Grid.Grid (p0 |> Dict.map (\_ -> migrate_GridCell_Cell migrate_a))


migrate_Hyperlink_Hyperlink : Evergreen.V115.Hyperlink.Hyperlink -> Evergreen.V116.Hyperlink.Hyperlink
migrate_Hyperlink_Hyperlink old =
    case old of
        Evergreen.V115.Hyperlink.Hyperlink p0 ->
            Evergreen.V116.Hyperlink.Hyperlink p0


migrate_IdDict_IdDict : (k_old -> k_new) -> (v_old -> v_new) -> Evergreen.V115.IdDict.IdDict k_old v_old -> Evergreen.V116.IdDict.IdDict k_new v_new
migrate_IdDict_IdDict migrate_k migrate_v old =
    case old of
        Evergreen.V115.IdDict.RBNode_elm_builtin p0 p1 p2 p3 p4 ->
            Evergreen.V116.IdDict.RBNode_elm_builtin (p0 |> migrate_IdDict_NColor)
                p1
                (p2 |> migrate_v)
                (p3 |> migrate_IdDict_IdDict migrate_k migrate_v)
                (p4 |> migrate_IdDict_IdDict migrate_k migrate_v)

        Evergreen.V115.IdDict.RBEmpty_elm_builtin ->
            Evergreen.V116.IdDict.RBEmpty_elm_builtin


migrate_IdDict_NColor : Evergreen.V115.IdDict.NColor -> Evergreen.V116.IdDict.NColor
migrate_IdDict_NColor old =
    case old of
        Evergreen.V115.IdDict.Red ->
            Evergreen.V116.IdDict.Red

        Evergreen.V115.IdDict.Black ->
            Evergreen.V116.IdDict.Black


migrate_Id_AnimalId : Evergreen.V115.Id.AnimalId -> Evergreen.V116.Id.AnimalId
migrate_Id_AnimalId old =
    case old of
        Evergreen.V115.Id.CowId p0 ->
            Evergreen.V116.Id.CowId p0


migrate_Id_Id : (a_old -> a_new) -> Evergreen.V115.Id.Id a_old -> Evergreen.V116.Id.Id a_new
migrate_Id_Id migrate_a old =
    case old of
        Evergreen.V115.Id.Id p0 ->
            Evergreen.V116.Id.Id p0


migrate_Id_MailId : Evergreen.V115.Id.MailId -> Evergreen.V116.Id.MailId
migrate_Id_MailId old =
    case old of
        Evergreen.V115.Id.MailId p0 ->
            Evergreen.V116.Id.MailId p0


migrate_Id_OneTimePasswordId : Evergreen.V115.Id.OneTimePasswordId -> Evergreen.V116.Id.OneTimePasswordId
migrate_Id_OneTimePasswordId old =
    case old of
        Evergreen.V115.Id.OneTimePasswordId p0 ->
            Evergreen.V116.Id.OneTimePasswordId p0


migrate_Id_PersonId : Evergreen.V115.Id.PersonId -> Evergreen.V116.Id.PersonId
migrate_Id_PersonId old =
    case old of
        Evergreen.V115.Id.PersonId p0 ->
            Evergreen.V116.Id.PersonId p0


migrate_Id_SecretId : (a_old -> a_new) -> Evergreen.V115.Id.SecretId a_old -> Evergreen.V116.Id.SecretId a_new
migrate_Id_SecretId migrate_a old =
    case old of
        Evergreen.V115.Id.SecretId p0 ->
            Evergreen.V116.Id.SecretId p0


migrate_Id_TrainId : Evergreen.V115.Id.TrainId -> Evergreen.V116.Id.TrainId
migrate_Id_TrainId old =
    case old of
        Evergreen.V115.Id.TrainId p0 ->
            Evergreen.V116.Id.TrainId p0


migrate_Id_UserId : Evergreen.V115.Id.UserId -> Evergreen.V116.Id.UserId
migrate_Id_UserId old =
    case old of
        Evergreen.V115.Id.UserId p0 ->
            Evergreen.V116.Id.UserId p0


migrate_List_Nonempty_Nonempty : (a_old -> a_new) -> List.Nonempty.Nonempty a_old -> List.Nonempty.Nonempty a_new
migrate_List_Nonempty_Nonempty migrate_a old =
    old |> List.Nonempty.map migrate_a


migrate_MailEditor_BackendMail : Evergreen.V115.MailEditor.BackendMail -> Evergreen.V116.MailEditor.BackendMail
migrate_MailEditor_BackendMail old =
    { content = old.content |> List.map migrate_MailEditor_Content
    , status = old.status |> migrate_MailEditor_MailStatus
    , from = old.from |> migrate_Id_Id migrate_Id_UserId
    , to = old.to |> migrate_Id_Id migrate_Id_UserId
    }


migrate_MailEditor_Content : Evergreen.V115.MailEditor.Content -> Evergreen.V116.MailEditor.Content
migrate_MailEditor_Content old =
    case old of
        Evergreen.V115.MailEditor.ImageType p0 p1 ->
            Evergreen.V116.MailEditor.ImageType p0 (p1 |> migrate_MailEditor_Image)

        Evergreen.V115.MailEditor.TextType p0 p1 ->
            Evergreen.V116.MailEditor.TextType p0 p1


migrate_MailEditor_Image : Evergreen.V115.MailEditor.Image -> Evergreen.V116.MailEditor.Image
migrate_MailEditor_Image old =
    case old of
        Evergreen.V115.MailEditor.Stamp p0 ->
            Evergreen.V116.MailEditor.Stamp (p0 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.SunglassesEmoji p0 ->
            Evergreen.V116.MailEditor.SunglassesEmoji (p0 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.NormalEmoji p0 ->
            Evergreen.V116.MailEditor.NormalEmoji (p0 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.SadEmoji p0 ->
            Evergreen.V116.MailEditor.SadEmoji (p0 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.Man p0 ->
            Evergreen.V116.MailEditor.Man (p0 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.TileImage p0 p1 p2 ->
            Evergreen.V116.MailEditor.TileImage (p0 |> migrate_Tile_TileGroup)
                p1
                (p2 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.Grass ->
            Evergreen.V116.MailEditor.Grass

        Evergreen.V115.MailEditor.DefaultCursor p0 ->
            Evergreen.V116.MailEditor.DefaultCursor (p0 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.DragCursor p0 ->
            Evergreen.V116.MailEditor.DragCursor (p0 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.PinchCursor p0 ->
            Evergreen.V116.MailEditor.PinchCursor (p0 |> migrate_Color_Colors)

        Evergreen.V115.MailEditor.Line p0 p1 ->
            Evergreen.V116.MailEditor.Line p0 (p1 |> migrate_Color_Color)

        Evergreen.V115.MailEditor.Animal p0 p1 ->
            Evergreen.V116.MailEditor.Animal (p0 |> migrate_Animal_AnimalType)
                (p1 |> migrate_Color_Colors)


migrate_MailEditor_MailStatus : Evergreen.V115.MailEditor.MailStatus -> Evergreen.V116.MailEditor.MailStatus
migrate_MailEditor_MailStatus old =
    case old of
        Evergreen.V115.MailEditor.MailWaitingPickup ->
            Evergreen.V116.MailEditor.MailWaitingPickup

        Evergreen.V115.MailEditor.MailInTransit p0 ->
            Evergreen.V116.MailEditor.MailInTransit (p0 |> migrate_Id_Id migrate_Id_TrainId)

        Evergreen.V115.MailEditor.MailReceived p0 ->
            Evergreen.V116.MailEditor.MailReceived p0

        Evergreen.V115.MailEditor.MailReceivedAndViewed p0 ->
            Evergreen.V116.MailEditor.MailReceivedAndViewed p0

        Evergreen.V115.MailEditor.MailDeletedByAdmin p0 ->
            Evergreen.V116.MailEditor.MailDeletedByAdmin
                { previousStatus = p0.previousStatus |> migrate_MailEditor_MailStatus2
                , deletedAt = p0.deletedAt
                }


migrate_MailEditor_MailStatus2 : Evergreen.V115.MailEditor.MailStatus2 -> Evergreen.V116.MailEditor.MailStatus2
migrate_MailEditor_MailStatus2 old =
    case old of
        Evergreen.V115.MailEditor.MailWaitingPickup2 ->
            Evergreen.V116.MailEditor.MailWaitingPickup2

        Evergreen.V115.MailEditor.MailInTransit2 p0 ->
            Evergreen.V116.MailEditor.MailInTransit2 (p0 |> migrate_Id_Id migrate_Id_TrainId)

        Evergreen.V115.MailEditor.MailReceived2 p0 ->
            Evergreen.V116.MailEditor.MailReceived2 p0

        Evergreen.V115.MailEditor.MailReceivedAndViewed2 p0 ->
            Evergreen.V116.MailEditor.MailReceivedAndViewed2 p0


migrate_PersonName_PersonName : Evergreen.V115.PersonName.PersonName -> Evergreen.V116.PersonName.PersonName
migrate_PersonName_PersonName old =
    case old of
        Evergreen.V115.PersonName.PersonName p0 ->
            Evergreen.V116.PersonName.PersonName p0


migrate_Point2d_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V115.Point2d.Point2d units_old coordinates_old -> Evergreen.V116.Point2d.Point2d units_new coordinates_new
migrate_Point2d_Point2d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Point2d migrate_units migrate_coordinates


migrate_Postmark_PostmarkSendResponse : Evergreen.V115.Postmark.PostmarkSendResponse -> Evergreen.V116.Postmark.PostmarkSendResponse
migrate_Postmark_PostmarkSendResponse old =
    old


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_Route_InviteToken : Evergreen.V115.Route.InviteToken -> Evergreen.V116.Route.InviteToken
migrate_Route_InviteToken old =
    case old of
        Evergreen.V115.Route.InviteToken p0 ->
            Evergreen.V116.Route.InviteToken p0


migrate_Route_LoginToken : Evergreen.V115.Route.LoginToken -> Evergreen.V116.Route.LoginToken
migrate_Route_LoginToken old =
    case old of
        Evergreen.V115.Route.LoginToken p0 ->
            Evergreen.V116.Route.LoginToken p0


migrate_TextInputMultiline_State : Evergreen.V115.TextInputMultiline.State -> Evergreen.V116.TextInputMultiline.State
migrate_TextInputMultiline_State old =
    old


migrate_TextInput_State : Evergreen.V115.TextInput.State -> Evergreen.V116.TextInput.State
migrate_TextInput_State old =
    old


migrate_TileCountBot_Model : Evergreen.V115.TileCountBot.Model -> Evergreen.V116.TileCountBot.Model
migrate_TileCountBot_Model old =
    { userId = old.userId |> migrate_Id_Id migrate_Id_UserId
    , tileUsage = old.tileUsage |> migrate_AssocList_Dict migrate_Tile_TileGroup identity
    , changedCells = old.changedCells |> Dict.map (\_ -> List.map migrate_GridCell_Value)
    }


migrate_Tile_RailPath : Evergreen.V115.Tile.RailPath -> Evergreen.V116.Tile.RailPath
migrate_Tile_RailPath old =
    case old of
        Evergreen.V115.Tile.RailPathHorizontal p0 ->
            Evergreen.V116.Tile.RailPathHorizontal p0

        Evergreen.V115.Tile.RailPathVertical p0 ->
            Evergreen.V116.Tile.RailPathVertical p0

        Evergreen.V115.Tile.RailPathBottomToRight ->
            Evergreen.V116.Tile.RailPathBottomToRight

        Evergreen.V115.Tile.RailPathBottomToLeft ->
            Evergreen.V116.Tile.RailPathBottomToLeft

        Evergreen.V115.Tile.RailPathTopToRight ->
            Evergreen.V116.Tile.RailPathTopToRight

        Evergreen.V115.Tile.RailPathTopToLeft ->
            Evergreen.V116.Tile.RailPathTopToLeft

        Evergreen.V115.Tile.RailPathBottomToRightLarge ->
            Evergreen.V116.Tile.RailPathBottomToRightLarge

        Evergreen.V115.Tile.RailPathBottomToLeftLarge ->
            Evergreen.V116.Tile.RailPathBottomToLeftLarge

        Evergreen.V115.Tile.RailPathTopToRightLarge ->
            Evergreen.V116.Tile.RailPathTopToRightLarge

        Evergreen.V115.Tile.RailPathTopToLeftLarge ->
            Evergreen.V116.Tile.RailPathTopToLeftLarge

        Evergreen.V115.Tile.RailPathStrafeDown ->
            Evergreen.V116.Tile.RailPathStrafeDown

        Evergreen.V115.Tile.RailPathStrafeUp ->
            Evergreen.V116.Tile.RailPathStrafeUp

        Evergreen.V115.Tile.RailPathStrafeLeft ->
            Evergreen.V116.Tile.RailPathStrafeLeft

        Evergreen.V115.Tile.RailPathStrafeRight ->
            Evergreen.V116.Tile.RailPathStrafeRight

        Evergreen.V115.Tile.RailPathStrafeDownSmall ->
            Evergreen.V116.Tile.RailPathStrafeDownSmall

        Evergreen.V115.Tile.RailPathStrafeUpSmall ->
            Evergreen.V116.Tile.RailPathStrafeUpSmall

        Evergreen.V115.Tile.RailPathStrafeLeftSmall ->
            Evergreen.V116.Tile.RailPathStrafeLeftSmall

        Evergreen.V115.Tile.RailPathStrafeRightSmall ->
            Evergreen.V116.Tile.RailPathStrafeRightSmall


migrate_Tile_Tile : Evergreen.V115.Tile.Tile -> Evergreen.V116.Tile.Tile
migrate_Tile_Tile old =
    case old of
        Evergreen.V115.Tile.EmptyTile ->
            Evergreen.V116.Tile.EmptyTile

        Evergreen.V115.Tile.HouseDown ->
            Evergreen.V116.Tile.HouseDown

        Evergreen.V115.Tile.HouseRight ->
            Evergreen.V116.Tile.HouseRight

        Evergreen.V115.Tile.HouseUp ->
            Evergreen.V116.Tile.HouseUp

        Evergreen.V115.Tile.HouseLeft ->
            Evergreen.V116.Tile.HouseLeft

        Evergreen.V115.Tile.RailHorizontal ->
            Evergreen.V116.Tile.RailHorizontal

        Evergreen.V115.Tile.RailVertical ->
            Evergreen.V116.Tile.RailVertical

        Evergreen.V115.Tile.RailBottomToRight ->
            Evergreen.V116.Tile.RailBottomToRight

        Evergreen.V115.Tile.RailBottomToLeft ->
            Evergreen.V116.Tile.RailBottomToLeft

        Evergreen.V115.Tile.RailTopToRight ->
            Evergreen.V116.Tile.RailTopToRight

        Evergreen.V115.Tile.RailTopToLeft ->
            Evergreen.V116.Tile.RailTopToLeft

        Evergreen.V115.Tile.RailBottomToRightLarge ->
            Evergreen.V116.Tile.RailBottomToRightLarge

        Evergreen.V115.Tile.RailBottomToLeftLarge ->
            Evergreen.V116.Tile.RailBottomToLeftLarge

        Evergreen.V115.Tile.RailTopToRightLarge ->
            Evergreen.V116.Tile.RailTopToRightLarge

        Evergreen.V115.Tile.RailTopToLeftLarge ->
            Evergreen.V116.Tile.RailTopToLeftLarge

        Evergreen.V115.Tile.RailCrossing ->
            Evergreen.V116.Tile.RailCrossing

        Evergreen.V115.Tile.RailStrafeDown ->
            Evergreen.V116.Tile.RailStrafeDown

        Evergreen.V115.Tile.RailStrafeUp ->
            Evergreen.V116.Tile.RailStrafeUp

        Evergreen.V115.Tile.RailStrafeLeft ->
            Evergreen.V116.Tile.RailStrafeLeft

        Evergreen.V115.Tile.RailStrafeRight ->
            Evergreen.V116.Tile.RailStrafeRight

        Evergreen.V115.Tile.TrainHouseRight ->
            Evergreen.V116.Tile.TrainHouseRight

        Evergreen.V115.Tile.TrainHouseLeft ->
            Evergreen.V116.Tile.TrainHouseLeft

        Evergreen.V115.Tile.RailStrafeDownSmall ->
            Evergreen.V116.Tile.RailStrafeDownSmall

        Evergreen.V115.Tile.RailStrafeUpSmall ->
            Evergreen.V116.Tile.RailStrafeUpSmall

        Evergreen.V115.Tile.RailStrafeLeftSmall ->
            Evergreen.V116.Tile.RailStrafeLeftSmall

        Evergreen.V115.Tile.RailStrafeRightSmall ->
            Evergreen.V116.Tile.RailStrafeRightSmall

        Evergreen.V115.Tile.Sidewalk ->
            Evergreen.V116.Tile.Sidewalk

        Evergreen.V115.Tile.SidewalkHorizontalRailCrossing ->
            Evergreen.V116.Tile.SidewalkHorizontalRailCrossing

        Evergreen.V115.Tile.SidewalkVerticalRailCrossing ->
            Evergreen.V116.Tile.SidewalkVerticalRailCrossing

        Evergreen.V115.Tile.RailBottomToRight_SplitLeft ->
            Evergreen.V116.Tile.RailBottomToRight_SplitLeft

        Evergreen.V115.Tile.RailBottomToLeft_SplitUp ->
            Evergreen.V116.Tile.RailBottomToLeft_SplitUp

        Evergreen.V115.Tile.RailTopToRight_SplitDown ->
            Evergreen.V116.Tile.RailTopToRight_SplitDown

        Evergreen.V115.Tile.RailTopToLeft_SplitRight ->
            Evergreen.V116.Tile.RailTopToLeft_SplitRight

        Evergreen.V115.Tile.RailBottomToRight_SplitUp ->
            Evergreen.V116.Tile.RailBottomToRight_SplitUp

        Evergreen.V115.Tile.RailBottomToLeft_SplitRight ->
            Evergreen.V116.Tile.RailBottomToLeft_SplitRight

        Evergreen.V115.Tile.RailTopToRight_SplitLeft ->
            Evergreen.V116.Tile.RailTopToRight_SplitLeft

        Evergreen.V115.Tile.RailTopToLeft_SplitDown ->
            Evergreen.V116.Tile.RailTopToLeft_SplitDown

        Evergreen.V115.Tile.PostOffice ->
            Evergreen.V116.Tile.PostOffice

        Evergreen.V115.Tile.PineTree1 ->
            Evergreen.V116.Tile.PineTree1

        Evergreen.V115.Tile.PineTree2 ->
            Evergreen.V116.Tile.PineTree2

        Evergreen.V115.Tile.BigPineTree ->
            Evergreen.V116.Tile.BigPineTree

        Evergreen.V115.Tile.LogCabinDown ->
            Evergreen.V116.Tile.LogCabinDown

        Evergreen.V115.Tile.LogCabinRight ->
            Evergreen.V116.Tile.LogCabinRight

        Evergreen.V115.Tile.LogCabinUp ->
            Evergreen.V116.Tile.LogCabinUp

        Evergreen.V115.Tile.LogCabinLeft ->
            Evergreen.V116.Tile.LogCabinLeft

        Evergreen.V115.Tile.RoadHorizontal ->
            Evergreen.V116.Tile.RoadHorizontal

        Evergreen.V115.Tile.RoadVertical ->
            Evergreen.V116.Tile.RoadVertical

        Evergreen.V115.Tile.RoadBottomToLeft ->
            Evergreen.V116.Tile.RoadBottomToLeft

        Evergreen.V115.Tile.RoadTopToLeft ->
            Evergreen.V116.Tile.RoadTopToLeft

        Evergreen.V115.Tile.RoadTopToRight ->
            Evergreen.V116.Tile.RoadTopToRight

        Evergreen.V115.Tile.RoadBottomToRight ->
            Evergreen.V116.Tile.RoadBottomToRight

        Evergreen.V115.Tile.Road4Way ->
            Evergreen.V116.Tile.Road4Way

        Evergreen.V115.Tile.RoadSidewalkCrossingHorizontal ->
            Evergreen.V116.Tile.RoadSidewalkCrossingHorizontal

        Evergreen.V115.Tile.RoadSidewalkCrossingVertical ->
            Evergreen.V116.Tile.RoadSidewalkCrossingVertical

        Evergreen.V115.Tile.Road3WayDown ->
            Evergreen.V116.Tile.Road3WayDown

        Evergreen.V115.Tile.Road3WayLeft ->
            Evergreen.V116.Tile.Road3WayLeft

        Evergreen.V115.Tile.Road3WayUp ->
            Evergreen.V116.Tile.Road3WayUp

        Evergreen.V115.Tile.Road3WayRight ->
            Evergreen.V116.Tile.Road3WayRight

        Evergreen.V115.Tile.RoadRailCrossingHorizontal ->
            Evergreen.V116.Tile.RoadRailCrossingHorizontal

        Evergreen.V115.Tile.RoadRailCrossingVertical ->
            Evergreen.V116.Tile.RoadRailCrossingVertical

        Evergreen.V115.Tile.FenceHorizontal ->
            Evergreen.V116.Tile.FenceHorizontal

        Evergreen.V115.Tile.FenceVertical ->
            Evergreen.V116.Tile.FenceVertical

        Evergreen.V115.Tile.FenceDiagonal ->
            Evergreen.V116.Tile.FenceDiagonal

        Evergreen.V115.Tile.FenceAntidiagonal ->
            Evergreen.V116.Tile.FenceAntidiagonal

        Evergreen.V115.Tile.RoadDeadendUp ->
            Evergreen.V116.Tile.RoadDeadendUp

        Evergreen.V115.Tile.RoadDeadendDown ->
            Evergreen.V116.Tile.RoadDeadendDown

        Evergreen.V115.Tile.BusStopDown ->
            Evergreen.V116.Tile.BusStopDown

        Evergreen.V115.Tile.BusStopLeft ->
            Evergreen.V116.Tile.BusStopLeft

        Evergreen.V115.Tile.BusStopRight ->
            Evergreen.V116.Tile.BusStopRight

        Evergreen.V115.Tile.BusStopUp ->
            Evergreen.V116.Tile.BusStopUp

        Evergreen.V115.Tile.HospitalDown ->
            Evergreen.V116.Tile.HospitalDown

        Evergreen.V115.Tile.HospitalLeft ->
            Evergreen.V116.Tile.HospitalLeft

        Evergreen.V115.Tile.HospitalUp ->
            Evergreen.V116.Tile.HospitalUp

        Evergreen.V115.Tile.HospitalRight ->
            Evergreen.V116.Tile.HospitalRight

        Evergreen.V115.Tile.Statue ->
            Evergreen.V116.Tile.Statue

        Evergreen.V115.Tile.HedgeRowDown ->
            Evergreen.V116.Tile.HedgeRowDown

        Evergreen.V115.Tile.HedgeRowLeft ->
            Evergreen.V116.Tile.HedgeRowLeft

        Evergreen.V115.Tile.HedgeRowRight ->
            Evergreen.V116.Tile.HedgeRowRight

        Evergreen.V115.Tile.HedgeRowUp ->
            Evergreen.V116.Tile.HedgeRowUp

        Evergreen.V115.Tile.HedgeCornerDownLeft ->
            Evergreen.V116.Tile.HedgeCornerDownLeft

        Evergreen.V115.Tile.HedgeCornerDownRight ->
            Evergreen.V116.Tile.HedgeCornerDownRight

        Evergreen.V115.Tile.HedgeCornerUpLeft ->
            Evergreen.V116.Tile.HedgeCornerUpLeft

        Evergreen.V115.Tile.HedgeCornerUpRight ->
            Evergreen.V116.Tile.HedgeCornerUpRight

        Evergreen.V115.Tile.HedgePillarDownLeft ->
            Evergreen.V116.Tile.HedgePillarDownLeft

        Evergreen.V115.Tile.HedgePillarDownRight ->
            Evergreen.V116.Tile.HedgePillarDownRight

        Evergreen.V115.Tile.HedgePillarUpLeft ->
            Evergreen.V116.Tile.HedgePillarUpLeft

        Evergreen.V115.Tile.HedgePillarUpRight ->
            Evergreen.V116.Tile.HedgePillarUpRight

        Evergreen.V115.Tile.ApartmentDown ->
            Evergreen.V116.Tile.ApartmentDown

        Evergreen.V115.Tile.ApartmentLeft ->
            Evergreen.V116.Tile.ApartmentLeft

        Evergreen.V115.Tile.ApartmentRight ->
            Evergreen.V116.Tile.ApartmentRight

        Evergreen.V115.Tile.ApartmentUp ->
            Evergreen.V116.Tile.ApartmentUp

        Evergreen.V115.Tile.RockDown ->
            Evergreen.V116.Tile.RockDown

        Evergreen.V115.Tile.RockLeft ->
            Evergreen.V116.Tile.RockLeft

        Evergreen.V115.Tile.RockRight ->
            Evergreen.V116.Tile.RockRight

        Evergreen.V115.Tile.RockUp ->
            Evergreen.V116.Tile.RockUp

        Evergreen.V115.Tile.Flowers1 ->
            Evergreen.V116.Tile.Flowers1

        Evergreen.V115.Tile.Flowers2 ->
            Evergreen.V116.Tile.Flowers2

        Evergreen.V115.Tile.ElmTree ->
            Evergreen.V116.Tile.ElmTree

        Evergreen.V115.Tile.DirtPathHorizontal ->
            Evergreen.V116.Tile.DirtPathHorizontal

        Evergreen.V115.Tile.DirtPathVertical ->
            Evergreen.V116.Tile.DirtPathVertical

        Evergreen.V115.Tile.BigText p0 ->
            Evergreen.V116.Tile.BigText p0

        Evergreen.V115.Tile.HyperlinkTile p0 ->
            Evergreen.V116.Tile.HyperlinkTile (p0 |> migrate_Hyperlink_Hyperlink)

        Evergreen.V115.Tile.BenchDown ->
            Evergreen.V116.Tile.BenchDown

        Evergreen.V115.Tile.BenchLeft ->
            Evergreen.V116.Tile.BenchLeft

        Evergreen.V115.Tile.BenchUp ->
            Evergreen.V116.Tile.BenchUp

        Evergreen.V115.Tile.BenchRight ->
            Evergreen.V116.Tile.BenchRight

        Evergreen.V115.Tile.ParkingDown ->
            Evergreen.V116.Tile.ParkingDown

        Evergreen.V115.Tile.ParkingLeft ->
            Evergreen.V116.Tile.ParkingLeft

        Evergreen.V115.Tile.ParkingUp ->
            Evergreen.V116.Tile.ParkingUp

        Evergreen.V115.Tile.ParkingRight ->
            Evergreen.V116.Tile.ParkingRight

        Evergreen.V115.Tile.ParkingRoad ->
            Evergreen.V116.Tile.ParkingRoad

        Evergreen.V115.Tile.ParkingRoundabout ->
            Evergreen.V116.Tile.ParkingRoundabout

        Evergreen.V115.Tile.CornerHouseUpLeft ->
            Evergreen.V116.Tile.CornerHouseUpLeft

        Evergreen.V115.Tile.CornerHouseUpRight ->
            Evergreen.V116.Tile.CornerHouseUpRight

        Evergreen.V115.Tile.CornerHouseDownLeft ->
            Evergreen.V116.Tile.CornerHouseDownLeft

        Evergreen.V115.Tile.CornerHouseDownRight ->
            Evergreen.V116.Tile.CornerHouseDownRight

        Evergreen.V115.Tile.DogHouseDown ->
            Evergreen.V116.Tile.DogHouseDown

        Evergreen.V115.Tile.DogHouseRight ->
            Evergreen.V116.Tile.DogHouseRight

        Evergreen.V115.Tile.DogHouseUp ->
            Evergreen.V116.Tile.DogHouseUp

        Evergreen.V115.Tile.DogHouseLeft ->
            Evergreen.V116.Tile.DogHouseLeft

        Evergreen.V115.Tile.Mushroom1 ->
            Evergreen.V116.Tile.Mushroom1

        Evergreen.V115.Tile.Mushroom2 ->
            Evergreen.V116.Tile.Mushroom2

        Evergreen.V115.Tile.TreeStump1 ->
            Evergreen.V116.Tile.TreeStump1

        Evergreen.V115.Tile.TreeStump2 ->
            Evergreen.V116.Tile.TreeStump2

        Evergreen.V115.Tile.Sunflowers ->
            Evergreen.V116.Tile.Sunflowers

        Evergreen.V115.Tile.RailDeadEndLeft ->
            Evergreen.V116.Tile.RailDeadEndLeft

        Evergreen.V115.Tile.RailDeadEndRight ->
            Evergreen.V116.Tile.RailDeadEndRight

        Evergreen.V115.Tile.RailStrafeLeftToRight_SplitUp ->
            Evergreen.V116.Tile.RailStrafeLeftToRight_SplitUp

        Evergreen.V115.Tile.RailStrafeLeftToRight_SplitDown ->
            Evergreen.V116.Tile.RailStrafeLeftToRight_SplitDown

        Evergreen.V115.Tile.RailStrafeRightToLeft_SplitUp ->
            Evergreen.V116.Tile.RailStrafeRightToLeft_SplitUp

        Evergreen.V115.Tile.RailStrafeRightToLeft_SplitDown ->
            Evergreen.V116.Tile.RailStrafeRightToLeft_SplitDown

        Evergreen.V115.Tile.RailStrafeTopToBottom_SplitLeft ->
            Evergreen.V116.Tile.RailStrafeTopToBottom_SplitLeft

        Evergreen.V115.Tile.RailStrafeTopToBottom_SplitRight ->
            Evergreen.V116.Tile.RailStrafeTopToBottom_SplitRight

        Evergreen.V115.Tile.RailStrafeBottomToTop_SplitLeft ->
            Evergreen.V116.Tile.RailStrafeBottomToTop_SplitLeft

        Evergreen.V115.Tile.RailStrafeBottomToTop_SplitRight ->
            Evergreen.V116.Tile.RailStrafeBottomToTop_SplitRight

        Evergreen.V115.Tile.RoadManholeDown ->
            Evergreen.V116.Tile.RoadManholeDown

        Evergreen.V115.Tile.RoadManholeLeft ->
            Evergreen.V116.Tile.RoadManholeLeft

        Evergreen.V115.Tile.RoadManholeUp ->
            Evergreen.V116.Tile.RoadManholeUp

        Evergreen.V115.Tile.RoadManholeRight ->
            Evergreen.V116.Tile.RoadManholeRight

        Evergreen.V115.Tile.BerryBush1 ->
            Evergreen.V116.Tile.BerryBush1

        Evergreen.V115.Tile.BerryBush2 ->
            Evergreen.V116.Tile.BerryBush2

        Evergreen.V115.Tile.SmallHouseDown ->
            Evergreen.V116.Tile.SmallHouseDown

        Evergreen.V115.Tile.SmallHouseLeft ->
            Evergreen.V116.Tile.SmallHouseLeft

        Evergreen.V115.Tile.SmallHouseUp ->
            Evergreen.V116.Tile.SmallHouseUp

        Evergreen.V115.Tile.SmallHouseRight ->
            Evergreen.V116.Tile.SmallHouseRight

        Evergreen.V115.Tile.OfficeDown ->
            Evergreen.V116.Tile.OfficeDown

        Evergreen.V115.Tile.OfficeUp ->
            Evergreen.V116.Tile.OfficeUp

        Evergreen.V115.Tile.FireTruckGarage ->
            Evergreen.V116.Tile.FireTruckGarage

        Evergreen.V115.Tile.TownHouse0 ->
            Evergreen.V116.Tile.TownHouse0

        Evergreen.V115.Tile.TownHouse1 ->
            Evergreen.V116.Tile.TownHouse1

        Evergreen.V115.Tile.TownHouse2 ->
            Evergreen.V116.Tile.TownHouse2

        Evergreen.V115.Tile.TownHouse3 ->
            Evergreen.V116.Tile.TownHouse3

        Evergreen.V115.Tile.TownHouse4 ->
            Evergreen.V116.Tile.TownHouse4

        Evergreen.V115.Tile.RowHouse0 ->
            Evergreen.V116.Tile.RowHouse0

        Evergreen.V115.Tile.RowHouse1 ->
            Evergreen.V116.Tile.RowHouse1

        Evergreen.V115.Tile.RowHouse2 ->
            Evergreen.V116.Tile.RowHouse2

        Evergreen.V115.Tile.RowHouse3 ->
            Evergreen.V116.Tile.RowHouse3

        Evergreen.V115.Tile.WideParkingDown ->
            Evergreen.V116.Tile.WideParkingDown

        Evergreen.V115.Tile.WideParkingLeft ->
            Evergreen.V116.Tile.WideParkingLeft

        Evergreen.V115.Tile.WideParkingUp ->
            Evergreen.V116.Tile.WideParkingUp

        Evergreen.V115.Tile.WideParkingRight ->
            Evergreen.V116.Tile.WideParkingRight

        Evergreen.V115.Tile.Gazebo ->
            Evergreen.V116.Tile.Gazebo


migrate_Tile_TileGroup : Evergreen.V115.Tile.TileGroup -> Evergreen.V116.Tile.TileGroup
migrate_Tile_TileGroup old =
    case old of
        Evergreen.V115.Tile.EmptyTileGroup ->
            Evergreen.V116.Tile.EmptyTileGroup

        Evergreen.V115.Tile.HouseGroup ->
            Evergreen.V116.Tile.HouseGroup

        Evergreen.V115.Tile.RailStraightGroup ->
            Evergreen.V116.Tile.RailStraightGroup

        Evergreen.V115.Tile.RailTurnGroup ->
            Evergreen.V116.Tile.RailTurnGroup

        Evergreen.V115.Tile.RailTurnLargeGroup ->
            Evergreen.V116.Tile.RailTurnLargeGroup

        Evergreen.V115.Tile.RailStrafeGroup ->
            Evergreen.V116.Tile.RailStrafeGroup

        Evergreen.V115.Tile.RailStrafeSmallGroup ->
            Evergreen.V116.Tile.RailStrafeSmallGroup

        Evergreen.V115.Tile.RailCrossingGroup ->
            Evergreen.V116.Tile.RailCrossingGroup

        Evergreen.V115.Tile.TrainHouseGroup ->
            Evergreen.V116.Tile.TrainHouseGroup

        Evergreen.V115.Tile.SidewalkGroup ->
            Evergreen.V116.Tile.SidewalkGroup

        Evergreen.V115.Tile.SidewalkRailGroup ->
            Evergreen.V116.Tile.SidewalkRailGroup

        Evergreen.V115.Tile.RailTurnSplitGroup ->
            Evergreen.V116.Tile.RailTurnSplitGroup

        Evergreen.V115.Tile.RailTurnSplitMirrorGroup ->
            Evergreen.V116.Tile.RailTurnSplitMirrorGroup

        Evergreen.V115.Tile.PostOfficeGroup ->
            Evergreen.V116.Tile.PostOfficeGroup

        Evergreen.V115.Tile.PineTreeGroup ->
            Evergreen.V116.Tile.PineTreeGroup

        Evergreen.V115.Tile.BigPineTreeGroup ->
            Evergreen.V116.Tile.BigPineTreeGroup

        Evergreen.V115.Tile.LogCabinGroup ->
            Evergreen.V116.Tile.LogCabinGroup

        Evergreen.V115.Tile.RoadStraightGroup ->
            Evergreen.V116.Tile.RoadStraightGroup

        Evergreen.V115.Tile.RoadTurnGroup ->
            Evergreen.V116.Tile.RoadTurnGroup

        Evergreen.V115.Tile.Road4WayGroup ->
            Evergreen.V116.Tile.Road4WayGroup

        Evergreen.V115.Tile.RoadSidewalkCrossingGroup ->
            Evergreen.V116.Tile.RoadSidewalkCrossingGroup

        Evergreen.V115.Tile.Road3WayGroup ->
            Evergreen.V116.Tile.Road3WayGroup

        Evergreen.V115.Tile.RoadRailCrossingGroup ->
            Evergreen.V116.Tile.RoadRailCrossingGroup

        Evergreen.V115.Tile.RoadDeadendGroup ->
            Evergreen.V116.Tile.RoadDeadendGroup

        Evergreen.V115.Tile.FenceStraightGroup ->
            Evergreen.V116.Tile.FenceStraightGroup

        Evergreen.V115.Tile.BusStopGroup ->
            Evergreen.V116.Tile.BusStopGroup

        Evergreen.V115.Tile.HospitalGroup ->
            Evergreen.V116.Tile.HospitalGroup

        Evergreen.V115.Tile.StatueGroup ->
            Evergreen.V116.Tile.StatueGroup

        Evergreen.V115.Tile.HedgeRowGroup ->
            Evergreen.V116.Tile.HedgeRowGroup

        Evergreen.V115.Tile.HedgeCornerGroup ->
            Evergreen.V116.Tile.HedgeCornerGroup

        Evergreen.V115.Tile.HedgePillarGroup ->
            Evergreen.V116.Tile.HedgePillarGroup

        Evergreen.V115.Tile.ApartmentGroup ->
            Evergreen.V116.Tile.ApartmentGroup

        Evergreen.V115.Tile.RockGroup ->
            Evergreen.V116.Tile.RockGroup

        Evergreen.V115.Tile.FlowersGroup ->
            Evergreen.V116.Tile.FlowersGroup

        Evergreen.V115.Tile.ElmTreeGroup ->
            Evergreen.V116.Tile.ElmTreeGroup

        Evergreen.V115.Tile.DirtPathGroup ->
            Evergreen.V116.Tile.DirtPathGroup

        Evergreen.V115.Tile.BigTextGroup ->
            Evergreen.V116.Tile.BigTextGroup

        Evergreen.V115.Tile.HyperlinkGroup ->
            Evergreen.V116.Tile.HyperlinkGroup

        Evergreen.V115.Tile.BenchGroup ->
            Evergreen.V116.Tile.BenchGroup

        Evergreen.V115.Tile.ParkingLotGroup ->
            Evergreen.V116.Tile.ParkingLotGroup

        Evergreen.V115.Tile.ParkingRoadGroup ->
            Evergreen.V116.Tile.ParkingRoadGroup

        Evergreen.V115.Tile.ParkingRoundaboutGroup ->
            Evergreen.V116.Tile.ParkingRoundaboutGroup

        Evergreen.V115.Tile.CornerHouseGroup ->
            Evergreen.V116.Tile.CornerHouseGroup

        Evergreen.V115.Tile.DogHouseGroup ->
            Evergreen.V116.Tile.DogHouseGroup

        Evergreen.V115.Tile.MushroomGroup ->
            Evergreen.V116.Tile.MushroomGroup

        Evergreen.V115.Tile.TreeStumpGroup ->
            Evergreen.V116.Tile.TreeStumpGroup

        Evergreen.V115.Tile.SunflowersGroup ->
            Evergreen.V116.Tile.SunflowersGroup

        Evergreen.V115.Tile.RailDeadendGroup ->
            Evergreen.V116.Tile.RailDeadendGroup

        Evergreen.V115.Tile.RailStrafeSplitGroup ->
            Evergreen.V116.Tile.RailStrafeSplitGroup

        Evergreen.V115.Tile.RailStrafeSplitMirrorGroup ->
            Evergreen.V116.Tile.RailStrafeSplitMirrorGroup

        Evergreen.V115.Tile.RoadStraightManholeGroup ->
            Evergreen.V116.Tile.RoadStraightManholeGroup

        Evergreen.V115.Tile.BerryBushGroup ->
            Evergreen.V116.Tile.BerryBushGroup

        Evergreen.V115.Tile.SmallHouseGroup ->
            Evergreen.V116.Tile.SmallHouseGroup

        Evergreen.V115.Tile.OfficeGroup ->
            Evergreen.V116.Tile.OfficeGroup

        Evergreen.V115.Tile.FireTruckGarageGroup ->
            Evergreen.V116.Tile.FireTruckGarageGroup

        Evergreen.V115.Tile.TownHouseGroup ->
            Evergreen.V116.Tile.TownHouseGroup

        Evergreen.V115.Tile.RowHouseGroup ->
            Evergreen.V116.Tile.RowHouseGroup

        Evergreen.V115.Tile.WideParkingLotGroup ->
            Evergreen.V116.Tile.WideParkingLotGroup

        Evergreen.V115.Tile.GazeboGroup ->
            Evergreen.V116.Tile.GazeboGroup


migrate_TimeOfDay_TimeOfDay : Evergreen.V115.TimeOfDay.TimeOfDay -> Evergreen.V116.TimeOfDay.TimeOfDay
migrate_TimeOfDay_TimeOfDay old =
    case old of
        Evergreen.V115.TimeOfDay.Automatic ->
            Evergreen.V116.TimeOfDay.Automatic

        Evergreen.V115.TimeOfDay.AlwaysDay ->
            Evergreen.V116.TimeOfDay.AlwaysDay

        Evergreen.V115.TimeOfDay.AlwaysNight ->
            Evergreen.V116.TimeOfDay.AlwaysNight


migrate_Train_IsStuckOrDerailed : Evergreen.V115.Train.IsStuckOrDerailed -> Evergreen.V116.Train.IsStuckOrDerailed
migrate_Train_IsStuckOrDerailed old =
    case old of
        Evergreen.V115.Train.IsStuck p0 ->
            Evergreen.V116.Train.IsStuck p0

        Evergreen.V115.Train.IsDerailed p0 p1 ->
            Evergreen.V116.Train.IsDerailed p0 (p1 |> migrate_Id_Id migrate_Id_TrainId)

        Evergreen.V115.Train.IsNotStuckOrDerailed ->
            Evergreen.V116.Train.IsNotStuckOrDerailed


migrate_Train_PreviousPath : Evergreen.V115.Train.PreviousPath -> Evergreen.V116.Train.PreviousPath
migrate_Train_PreviousPath old =
    { position = old.position |> migrate_Coord_Coord migrate_Units_WorldUnit
    , path = old.path |> migrate_Tile_RailPath
    , reversed = old.reversed
    }


migrate_Train_Status : Evergreen.V115.Train.Status -> Evergreen.V116.Train.Status
migrate_Train_Status old =
    case old of
        Evergreen.V115.Train.WaitingAtHome ->
            Evergreen.V116.Train.WaitingAtHome

        Evergreen.V115.Train.TeleportingHome p0 ->
            Evergreen.V116.Train.TeleportingHome p0

        Evergreen.V115.Train.Travelling ->
            Evergreen.V116.Train.Travelling

        Evergreen.V115.Train.StoppedAtPostOffice p0 ->
            Evergreen.V116.Train.StoppedAtPostOffice
                { time = p0.time
                , userId = p0.userId |> migrate_Id_Id migrate_Id_UserId
                }


migrate_Train_Train : Evergreen.V115.Train.Train -> Evergreen.V116.Train.Train
migrate_Train_Train old =
    case old of
        Evergreen.V115.Train.Train p0 ->
            Evergreen.V116.Train.Train
                { position = p0.position |> migrate_Coord_Coord migrate_Units_WorldUnit
                , path = p0.path |> migrate_Tile_RailPath
                , previousPaths = p0.previousPaths |> List.map migrate_Train_PreviousPath
                , t = p0.t
                , speed = p0.speed |> migrate_Quantity_Quantity
                , home = p0.home |> migrate_Coord_Coord migrate_Units_WorldUnit
                , homePath = p0.homePath |> migrate_Tile_RailPath
                , isStuckOrDerailed = p0.isStuckOrDerailed |> migrate_Train_IsStuckOrDerailed
                , status = p0.status |> migrate_Train_Status
                , owner = p0.owner |> migrate_Id_Id migrate_Id_UserId
                , color = p0.color |> migrate_Color_Color
                }


migrate_Types_BackendError : Evergreen.V115.Types.BackendError -> Evergreen.V116.Types.BackendError
migrate_Types_BackendError old =
    case old of
        Evergreen.V115.Types.PostmarkError p0 p1 ->
            Evergreen.V116.Types.PostmarkError (p0 |> migrate_EmailAddress_EmailAddress) p1

        Evergreen.V115.Types.UserNotFoundWhenLoggingIn p0 ->
            Evergreen.V116.Types.UserNotFoundWhenLoggingIn (p0 |> migrate_Id_Id migrate_Id_UserId)


migrate_Types_BackendUserData : Evergreen.V115.Types.BackendUserData -> Evergreen.V116.Types.BackendUserData
migrate_Types_BackendUserData old =
    { undoHistory = old.undoHistory
    , redoHistory = old.redoHistory
    , undoCurrent = old.undoCurrent
    , mailDrafts = old.mailDrafts |> migrate_IdDict_IdDict migrate_Id_UserId (List.map migrate_MailEditor_Content)
    , cursor = old.cursor |> Maybe.map migrate_Cursor_Cursor
    , handColor = old.handColor |> migrate_Color_Colors
    , userType = old.userType |> migrate_Types_BackendUserType
    , name = old.name |> migrate_DisplayName_DisplayName
    }


migrate_Types_BackendUserType : Evergreen.V115.Types.BackendUserType -> Evergreen.V116.Types.BackendUserType
migrate_Types_BackendUserType old =
    case old of
        Evergreen.V115.Types.HumanUser p0 ->
            Evergreen.V116.Types.HumanUser (p0 |> migrate_Types_HumanUserData)

        Evergreen.V115.Types.BotUser ->
            Evergreen.V116.Types.BotUser


migrate_Types_EmailResult : Evergreen.V115.Types.EmailResult -> Evergreen.V116.Types.EmailResult
migrate_Types_EmailResult old =
    case old of
        Evergreen.V115.Types.EmailSending ->
            Evergreen.V116.Types.EmailSending

        Evergreen.V115.Types.EmailSendFailed p0 ->
            Evergreen.V116.Types.EmailSendFailed p0

        Evergreen.V115.Types.EmailSent p0 ->
            Evergreen.V116.Types.EmailSent (p0 |> migrate_Postmark_PostmarkSendResponse)


migrate_Types_HumanUserData : Evergreen.V115.Types.HumanUserData -> Evergreen.V116.Types.HumanUserData
migrate_Types_HumanUserData old =
    { emailAddress = old.emailAddress |> migrate_EmailAddress_EmailAddress
    , acceptedInvites = old.acceptedInvites |> migrate_IdDict_IdDict migrate_Id_UserId identity
    , timeOfDay = old.timeOfDay |> migrate_TimeOfDay_TimeOfDay
    , tileHotkeys = old.tileHotkeys |> migrate_AssocList_Dict migrate_Change_TileHotkey migrate_Tile_TileGroup
    , showNotifications = old.showNotifications
    , notificationsClearedAt = old.notificationsClearedAt
    , allowEmailNotifications = old.allowEmailNotifications
    , hyperlinksVisited = Set.empty
    }


migrate_Types_Invite : Evergreen.V115.Types.Invite -> Evergreen.V116.Types.Invite
migrate_Types_Invite old =
    { invitedBy = old.invitedBy |> migrate_Id_Id migrate_Id_UserId
    , invitedAt = old.invitedAt
    , invitedEmailAddress = old.invitedEmailAddress |> migrate_EmailAddress_EmailAddress
    , emailResult = old.emailResult |> migrate_Types_EmailResult
    }


migrate_Types_Person : Evergreen.V115.Types.Person -> Evergreen.V116.Types.Person
migrate_Types_Person old =
    { name = old.name |> migrate_PersonName_PersonName
    , home = old.home |> migrate_Coord_Coord migrate_Units_WorldUnit
    , position = old.position |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit
    }


migrate_Ui_BorderAndFill : Evergreen.V115.Ui.BorderAndFill -> Evergreen.V116.Ui.BorderAndFill
migrate_Ui_BorderAndFill old =
    case old of
        Evergreen.V115.Ui.NoBorderOrFill ->
            Evergreen.V116.Ui.NoBorderOrFill

        Evergreen.V115.Ui.FillOnly p0 ->
            Evergreen.V116.Ui.FillOnly (p0 |> migrate_Color_Color)

        Evergreen.V115.Ui.BorderAndFill p0 ->
            Evergreen.V116.Ui.BorderAndFill
                { borderWidth = p0.borderWidth
                , borderColor = p0.borderColor |> migrate_Color_Color
                , fillColor = p0.fillColor |> migrate_Color_Color
                }


migrate_Ui_ButtonData : (id_old -> id_new) -> Evergreen.V115.Ui.ButtonData id_old -> Evergreen.V116.Ui.ButtonData id_new
migrate_Ui_ButtonData migrate_id old =
    { id = old.id |> migrate_id
    , padding = old.padding |> migrate_Ui_Padding
    , borderAndFill = old.borderAndFill |> migrate_Ui_BorderAndFill
    , borderAndFillFocus = old.borderAndFillFocus |> migrate_Ui_BorderAndFill
    , cachedSize = old.cachedSize
    , inFront = old.inFront |> List.map (migrate_Ui_Element migrate_id)
    }


migrate_Ui_Element : (id_old -> id_new) -> Evergreen.V115.Ui.Element id_old -> Evergreen.V116.Ui.Element id_new
migrate_Ui_Element migrate_id old =
    case old of
        Evergreen.V115.Ui.Text p0 ->
            Evergreen.V116.Ui.Text
                { outline = p0.outline |> Maybe.map migrate_Color_Color
                , color = p0.color |> migrate_Color_Color
                , scale = p0.scale
                , text = p0.text
                , underlined = p0.underlined
                , cachedSize = p0.cachedSize
                }

        Evergreen.V115.Ui.TextInput p0 ->
            Evergreen.V116.Ui.TextInput (p0 |> migrate_Ui_TextInputData migrate_id)

        Evergreen.V115.Ui.TextInputMultiline p0 ->
            Evergreen.V116.Ui.TextInputMultiline (p0 |> migrate_Ui_TextInputMultilineData migrate_id)

        Evergreen.V115.Ui.Button p0 p1 ->
            Evergreen.V116.Ui.Button (p0 |> migrate_Ui_ButtonData migrate_id)
                (p1 |> migrate_Ui_Element migrate_id)

        Evergreen.V115.Ui.Row p0 p1 ->
            Evergreen.V116.Ui.Row (p0 |> migrate_Ui_RowColumn)
                (p1 |> List.map (migrate_Ui_Element migrate_id))

        Evergreen.V115.Ui.Column p0 p1 ->
            Evergreen.V116.Ui.Column (p0 |> migrate_Ui_RowColumn)
                (p1 |> List.map (migrate_Ui_Element migrate_id))

        Evergreen.V115.Ui.Single p0 p1 ->
            Evergreen.V116.Ui.Single
                { padding = p0.padding |> migrate_Ui_Padding
                , borderAndFill = p0.borderAndFill |> migrate_Ui_BorderAndFill
                , inFront = p0.inFront |> List.map (migrate_Ui_Element migrate_id)
                , cachedSize = p0.cachedSize
                }
                (p1 |> migrate_Ui_Element migrate_id)

        Evergreen.V115.Ui.Quads p0 ->
            Evergreen.V116.Ui.Quads p0

        Evergreen.V115.Ui.Empty ->
            Evergreen.V116.Ui.Empty

        Evergreen.V115.Ui.IgnoreInputs p0 ->
            Evergreen.V116.Ui.IgnoreInputs (p0 |> migrate_Ui_Element migrate_id)


migrate_Ui_Padding : Evergreen.V115.Ui.Padding -> Evergreen.V116.Ui.Padding
migrate_Ui_Padding old =
    old


migrate_Ui_RowColumn : Evergreen.V115.Ui.RowColumn -> Evergreen.V116.Ui.RowColumn
migrate_Ui_RowColumn old =
    { spacing = old.spacing
    , padding = old.padding |> migrate_Ui_Padding
    , cachedSize = old.cachedSize
    }


migrate_Ui_TextInputData : (id_old -> id_new) -> Evergreen.V115.Ui.TextInputData id_old -> Evergreen.V116.Ui.TextInputData id_new
migrate_Ui_TextInputData migrate_id old =
    { id = old.id |> migrate_id
    , width = old.width
    , isValid = old.isValid
    , state = old.state |> migrate_TextInput_State
    , textScale = old.textScale
    }


migrate_Ui_TextInputMultilineData : (id_old -> id_new) -> Evergreen.V115.Ui.TextInputMultilineData id_old -> Evergreen.V116.Ui.TextInputMultilineData id_new
migrate_Ui_TextInputMultilineData migrate_id old =
    { id = old.id |> migrate_id
    , width = old.width
    , isValid = old.isValid
    , state = old.state |> migrate_TextInputMultiline_State
    , textScale = old.textScale
    , dummyField = old.dummyField
    }


migrate_Units_CellLocalUnit : Evergreen.V115.Units.CellLocalUnit -> Evergreen.V116.Units.CellLocalUnit
migrate_Units_CellLocalUnit old =
    case old of
        Evergreen.V115.Units.LocalUnit p0 ->
            Evergreen.V116.Units.LocalUnit p0


migrate_Units_CellUnit : Evergreen.V115.Units.CellUnit -> Evergreen.V116.Units.CellUnit
migrate_Units_CellUnit old =
    case old of
        Evergreen.V115.Units.CellUnit p0 ->
            Evergreen.V116.Units.CellUnit p0


migrate_Units_WorldUnit : Evergreen.V115.Units.WorldUnit -> Evergreen.V116.Units.WorldUnit
migrate_Units_WorldUnit old =
    case old of
        Evergreen.V115.Units.WorldUnit p0 ->
            Evergreen.V116.Units.WorldUnit p0
