module Evergreen.Migrate.V93 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import AssocList
import AssocSet
import Dict
import Effect.Time
import Evergreen.V91.AdminPage
import Evergreen.V91.Animal
import Evergreen.V91.Audio
import Evergreen.V91.Bounds
import Evergreen.V91.Change
import Evergreen.V91.Color
import Evergreen.V91.Coord
import Evergreen.V91.Cursor
import Evergreen.V91.DisplayName
import Evergreen.V91.EmailAddress
import Evergreen.V91.Geometry.Types
import Evergreen.V91.Grid
import Evergreen.V91.GridCell
import Evergreen.V91.Id
import Evergreen.V91.IdDict
import Evergreen.V91.Keyboard
import Evergreen.V91.LocalGrid
import Evergreen.V91.LocalModel
import Evergreen.V91.MailEditor
import Evergreen.V91.Point2d
import Evergreen.V91.Postmark
import Evergreen.V91.Route
import Evergreen.V91.Sound
import Evergreen.V91.TextInput
import Evergreen.V91.Tile
import Evergreen.V91.Tool
import Evergreen.V91.Train
import Evergreen.V91.Types
import Evergreen.V91.Ui
import Evergreen.V91.Units
import Evergreen.V91.Untrusted
import Evergreen.V91.User
import Evergreen.V93.AdminPage
import Evergreen.V93.Animal
import Evergreen.V93.Audio
import Evergreen.V93.Bounds
import Evergreen.V93.Change
import Evergreen.V93.Color
import Evergreen.V93.Coord
import Evergreen.V93.Cursor
import Evergreen.V93.DisplayName
import Evergreen.V93.EmailAddress
import Evergreen.V93.Geometry.Types
import Evergreen.V93.Grid
import Evergreen.V93.GridCell
import Evergreen.V93.Id
import Evergreen.V93.IdDict
import Evergreen.V93.Keyboard
import Evergreen.V93.LocalGrid
import Evergreen.V93.LocalModel
import Evergreen.V93.MailEditor
import Evergreen.V93.Point2d
import Evergreen.V93.Postmark
import Evergreen.V93.Route
import Evergreen.V93.Sound
import Evergreen.V93.TextInput
import Evergreen.V93.Tile
import Evergreen.V93.TimeOfDay
import Evergreen.V93.Tool
import Evergreen.V93.Train
import Evergreen.V93.Types
import Evergreen.V93.Ui
import Evergreen.V93.Units
import Evergreen.V93.Untrusted
import Evergreen.V93.User
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Maybe
import Quantity


frontendModel : Evergreen.V91.Types.FrontendModel -> ModelMigration Evergreen.V93.Types.FrontendModel Evergreen.V93.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V91.Types.BackendModel -> ModelMigration Evergreen.V93.Types.BackendModel Evergreen.V93.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V91.Types.FrontendMsg -> MsgMigration Evergreen.V93.Types.FrontendMsg Evergreen.V93.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V91.Types.ToBackend -> MsgMigration Evergreen.V93.Types.ToBackend Evergreen.V93.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V91.Types.BackendMsg -> MsgMigration Evergreen.V93.Types.BackendMsg Evergreen.V93.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V91.Types.ToFrontend -> MsgMigration Evergreen.V93.Types.ToFrontend Evergreen.V93.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V91.Types.BackendModel -> Evergreen.V93.Types.BackendModel
migrate_Types_BackendModel old =
    { grid = old.grid |> migrate_Grid_Grid
    , userSessions = Dict.empty
    , users = old.users |> migrate_IdDict_IdDict migrate_Id_UserId migrate_Types_BackendUserData
    , secretLinkCounter = old.secretLinkCounter
    , errors = old.errors |> List.map (Tuple.mapSecond migrate_Types_BackendError)
    , trains = old.trains |> migrate_IdDict_IdDict migrate_Id_TrainId migrate_Train_Train
    , cows = old.cows |> migrate_IdDict_IdDict migrate_Id_AnimalId migrate_Animal_Animal
    , lastWorldUpdateTrains = old.lastWorldUpdateTrains |> migrate_IdDict_IdDict migrate_Id_TrainId migrate_Train_Train
    , lastWorldUpdate = old.lastWorldUpdate
    , mail = old.mail |> migrate_IdDict_IdDict migrate_Id_MailId migrate_MailEditor_BackendMail
    , pendingLoginTokens =
        old.pendingLoginTokens
            |> migrate_AssocList_Dict (migrate_Id_SecretId migrate_Route_LoginToken)
                (\rec ->
                    { requestTime = rec.requestTime
                    , userId = rec.userId |> migrate_Id_Id migrate_Id_UserId
                    , requestedBy = rec.requestedBy |> migrate_Types_LoginRequestedBy
                    }
                )
    , invites = old.invites |> migrate_AssocList_Dict (migrate_Id_SecretId migrate_Route_InviteToken) migrate_Types_Invite
    , lastCacheRegeneration = old.lastCacheRegeneration
    , reported = old.reported |> migrate_IdDict_IdDict migrate_Id_UserId (migrate_List_Nonempty_Nonempty migrate_Change_BackendReport)
    , isGridReadOnly = old.isGridReadOnly
    , trainsDisabled = old.trainsDisabled |> migrate_Change_AreTrainsDisabled
    , lastReportEmailToAdmin = old.lastReportEmailToAdmin
    }


migrate_AdminPage_Hover : Evergreen.V91.AdminPage.Hover -> Evergreen.V93.AdminPage.Hover
migrate_AdminPage_Hover old =
    case old of
        Evergreen.V91.AdminPage.ToggleIsGridReadOnlyButton ->
            Evergreen.V93.AdminPage.ToggleIsGridReadOnlyButton

        Evergreen.V91.AdminPage.ToggleTrainsDisabledButton ->
            Evergreen.V93.AdminPage.ToggleTrainsDisabledButton

        Evergreen.V91.AdminPage.ResetConnectionsButton ->
            Evergreen.V93.AdminPage.ResetConnectionsButton

        Evergreen.V91.AdminPage.CloseAdminPage ->
            Evergreen.V93.AdminPage.CloseAdminPage

        Evergreen.V91.AdminPage.AdminMailPageButton p0 ->
            Evergreen.V93.AdminPage.AdminMailPageButton p0

        Evergreen.V91.AdminPage.RestoreMailButton p0 ->
            Evergreen.V93.AdminPage.RestoreMailButton (p0 |> migrate_Id_Id migrate_Id_MailId)

        Evergreen.V91.AdminPage.DeleteMailButton p0 ->
            Evergreen.V93.AdminPage.DeleteMailButton (p0 |> migrate_Id_Id migrate_Id_MailId)


migrate_AdminPage_Model : Evergreen.V91.AdminPage.Model -> Evergreen.V93.AdminPage.Model
migrate_AdminPage_Model old =
    old


migrate_Animal_Animal : Evergreen.V91.Animal.Animal -> Evergreen.V93.Animal.Animal
migrate_Animal_Animal old =
    { position = old.position |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit
    , animalType = old.animalType |> migrate_Animal_AnimalType
    }


migrate_Animal_AnimalType : Evergreen.V91.Animal.AnimalType -> Evergreen.V93.Animal.AnimalType
migrate_Animal_AnimalType old =
    case old of
        Evergreen.V91.Animal.Cow ->
            Evergreen.V93.Animal.Cow

        Evergreen.V91.Animal.Hamster ->
            Evergreen.V93.Animal.Hamster

        Evergreen.V91.Animal.Sheep ->
            Evergreen.V93.Animal.Sheep


migrate_AssocList_Dict : (a_old -> a_new) -> (b_old -> b_new) -> AssocList.Dict a_old b_old -> AssocList.Dict a_new b_new
migrate_AssocList_Dict migrate_a migrate_b old =
    old
        |> AssocList.toList
        |> List.map (Tuple.mapBoth migrate_a migrate_b)
        |> AssocList.fromList


migrate_AssocSet_Set : (a_old -> a_new) -> AssocSet.Set a_old -> AssocSet.Set a_new
migrate_AssocSet_Set migrate_a old =
    old |> AssocSet.map migrate_a


migrate_Bounds_Bounds : (unit_old -> unit_new) -> Evergreen.V91.Bounds.Bounds unit_old -> Evergreen.V93.Bounds.Bounds unit_new
migrate_Bounds_Bounds migrate_unit old =
    case old of
        Evergreen.V91.Bounds.Bounds p0 ->
            Evergreen.V93.Bounds.Bounds
                { min = p0.min |> migrate_Coord_Coord migrate_unit
                , max = p0.max |> migrate_Coord_Coord migrate_unit
                }


migrate_Change_AdminChange : Evergreen.V91.Change.AdminChange -> Evergreen.V93.Change.AdminChange
migrate_Change_AdminChange old =
    case old of
        Evergreen.V91.Change.AdminResetSessions ->
            Evergreen.V93.Change.AdminResetSessions

        Evergreen.V91.Change.AdminSetGridReadOnly p0 ->
            Evergreen.V93.Change.AdminSetGridReadOnly p0

        Evergreen.V91.Change.AdminSetTrainsDisabled p0 ->
            Evergreen.V93.Change.AdminSetTrainsDisabled (p0 |> migrate_Change_AreTrainsDisabled)

        Evergreen.V91.Change.AdminDeleteMail p0 p1 ->
            Evergreen.V93.Change.AdminDeleteMail (p0 |> migrate_Id_Id migrate_Id_MailId) p1

        Evergreen.V91.Change.AdminRestoreMail p0 ->
            Evergreen.V93.Change.AdminRestoreMail (p0 |> migrate_Id_Id migrate_Id_MailId)


migrate_Change_AdminData : Evergreen.V91.Change.AdminData -> Evergreen.V93.Change.AdminData
migrate_Change_AdminData old =
    { lastCacheRegeneration = old.lastCacheRegeneration
    , userSessions =
        old.userSessions
            |> List.map
                (\rec ->
                    { userId = rec.userId |> Maybe.map (migrate_Id_Id migrate_Id_UserId)
                    , connectionCount = rec.connectionCount
                    }
                )
    , reported = old.reported |> migrate_IdDict_IdDict migrate_Id_UserId (migrate_List_Nonempty_Nonempty migrate_Change_BackendReport)
    , mail = old.mail |> migrate_IdDict_IdDict migrate_Id_MailId migrate_MailEditor_BackendMail
    }


migrate_Change_AreTrainsDisabled : Evergreen.V91.Change.AreTrainsDisabled -> Evergreen.V93.Change.AreTrainsDisabled
migrate_Change_AreTrainsDisabled old =
    case old of
        Evergreen.V91.Change.TrainsDisabled ->
            Evergreen.V93.Change.TrainsDisabled

        Evergreen.V91.Change.TrainsEnabled ->
            Evergreen.V93.Change.TrainsEnabled


migrate_Change_BackendReport : Evergreen.V91.Change.BackendReport -> Evergreen.V93.Change.BackendReport
migrate_Change_BackendReport old =
    { reportedUser = old.reportedUser |> migrate_Id_Id migrate_Id_UserId
    , position = old.position |> migrate_Coord_Coord migrate_Units_WorldUnit
    , reportedAt = old.reportedAt
    }


migrate_Change_Change : Evergreen.V91.Change.Change -> Evergreen.V93.Change.Change
migrate_Change_Change old =
    case old of
        Evergreen.V91.Change.LocalChange p0 p1 ->
            Evergreen.V93.Change.LocalChange (p0 |> migrate_Id_Id migrate_Id_EventId)
                (p1 |> migrate_Change_LocalChange)

        Evergreen.V91.Change.ServerChange p0 ->
            Evergreen.V93.Change.ServerChange (p0 |> migrate_Change_ServerChange)

        Evergreen.V91.Change.ClientChange p0 ->
            Evergreen.V93.Change.LocalChange (Evergreen.V93.Id.Id -1) Evergreen.V93.Change.InvalidChange


migrate_Change_LocalChange : Evergreen.V91.Change.LocalChange -> Evergreen.V93.Change.LocalChange
migrate_Change_LocalChange old =
    case old of
        Evergreen.V91.Change.LocalGridChange p0 ->
            Evergreen.V93.Change.LocalGridChange (p0 |> migrate_Grid_LocalGridChange)

        Evergreen.V91.Change.LocalUndo ->
            Evergreen.V93.Change.LocalUndo

        Evergreen.V91.Change.LocalRedo ->
            Evergreen.V93.Change.LocalRedo

        Evergreen.V91.Change.LocalAddUndo ->
            Evergreen.V93.Change.LocalAddUndo

        Evergreen.V91.Change.PickupCow p0 p1 p2 ->
            Evergreen.V93.Change.PickupCow (p0 |> migrate_Id_Id migrate_Id_AnimalId)
                (p1 |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit)
                p2

        Evergreen.V91.Change.DropCow p0 p1 p2 ->
            Evergreen.V93.Change.DropCow (p0 |> migrate_Id_Id migrate_Id_AnimalId)
                (p1 |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit)
                p2

        Evergreen.V91.Change.MoveCursor p0 ->
            Evergreen.V93.Change.MoveCursor (p0 |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit)

        Evergreen.V91.Change.InvalidChange ->
            Evergreen.V93.Change.InvalidChange

        Evergreen.V91.Change.ChangeHandColor p0 ->
            Evergreen.V93.Change.ChangeHandColor (p0 |> migrate_Color_Colors)

        Evergreen.V91.Change.ToggleRailSplit p0 ->
            Evergreen.V93.Change.ToggleRailSplit (p0 |> migrate_Coord_Coord migrate_Units_WorldUnit)

        Evergreen.V91.Change.ChangeDisplayName p0 ->
            Evergreen.V93.Change.ChangeDisplayName (p0 |> migrate_DisplayName_DisplayName)

        Evergreen.V91.Change.SubmitMail p0 ->
            Evergreen.V93.Change.SubmitMail
                { content = p0.content |> List.map migrate_MailEditor_Content
                , to = p0.to |> migrate_Id_Id migrate_Id_UserId
                }

        Evergreen.V91.Change.UpdateDraft p0 ->
            Evergreen.V93.Change.UpdateDraft
                { content = p0.content |> List.map migrate_MailEditor_Content
                , to = p0.to |> migrate_Id_Id migrate_Id_UserId
                }

        Evergreen.V91.Change.TeleportHomeTrainRequest p0 p1 ->
            Evergreen.V93.Change.TeleportHomeTrainRequest (p0 |> migrate_Id_Id migrate_Id_TrainId) p1

        Evergreen.V91.Change.LeaveHomeTrainRequest p0 p1 ->
            Evergreen.V93.Change.LeaveHomeTrainRequest (p0 |> migrate_Id_Id migrate_Id_TrainId) p1

        Evergreen.V91.Change.ViewedMail p0 ->
            Evergreen.V93.Change.ViewedMail (p0 |> migrate_Id_Id migrate_Id_MailId)

        Evergreen.V91.Change.SetAllowEmailNotifications p0 ->
            Evergreen.V93.Change.SetAllowEmailNotifications p0

        Evergreen.V91.Change.ChangeTool p0 ->
            Evergreen.V93.Change.ChangeTool (p0 |> migrate_Cursor_OtherUsersTool)

        Evergreen.V91.Change.AdminChange p0 ->
            Evergreen.V93.Change.AdminChange (p0 |> migrate_Change_AdminChange)

        Evergreen.V91.Change.ReportVandalism p0 ->
            Evergreen.V93.Change.ReportVandalism (p0 |> migrate_Change_Report)

        Evergreen.V91.Change.RemoveReport p0 ->
            Evergreen.V93.Change.RemoveReport (p0 |> migrate_Coord_Coord migrate_Units_WorldUnit)

        Evergreen.V91.Change.SetTimeOfDay p0 ->
            Evergreen.V93.Change.SetTimeOfDay (p0 |> migrate_TimeOfDay_TimeOfDay)

        Evergreen.V91.Change.SetTileHotkey p0 p1 ->
            Evergreen.V93.Change.SetTileHotkey (p0 |> migrate_Change_TileHotkey)
                (p1 |> migrate_Tile_TileGroup)


migrate_Change_LoggedIn_ : Evergreen.V91.Change.LoggedIn_ -> Evergreen.V93.Change.LoggedIn_
migrate_Change_LoggedIn_ old =
    { userId = old.userId |> migrate_Id_Id migrate_Id_UserId
    , undoHistory = old.undoHistory
    , redoHistory = old.redoHistory
    , undoCurrent = old.undoCurrent
    , mailDrafts = old.mailDrafts |> migrate_IdDict_IdDict migrate_Id_UserId (List.map migrate_MailEditor_Content)
    , emailAddress = old.emailAddress |> migrate_EmailAddress_EmailAddress
    , inbox = old.inbox |> migrate_IdDict_IdDict migrate_Id_MailId migrate_MailEditor_ReceivedMail
    , allowEmailNotifications = old.allowEmailNotifications
    , adminData = old.adminData |> Maybe.map migrate_Change_AdminData
    , reports = old.reports |> List.map migrate_Change_Report
    , isGridReadOnly = old.isGridReadOnly
    , timeOfDay = old.timeOfDay |> migrate_TimeOfDay_TimeOfDay
    , tileHotkeys = old.tileHotkeys |> migrate_AssocList_Dict migrate_Change_TileHotkey migrate_Tile_TileGroup
    , showNotifications = False
    , notifications = []
    , notificationsClearedAt = Effect.Time.millisToPosix 1697325179000
    }


migrate_Change_NotLoggedIn_ : Evergreen.V91.Change.NotLoggedIn_ -> Evergreen.V93.Change.NotLoggedIn_
migrate_Change_NotLoggedIn_ old =
    { timeOfDay = old.timeOfDay |> migrate_TimeOfDay_TimeOfDay
    }


migrate_Change_Report : Evergreen.V91.Change.Report -> Evergreen.V93.Change.Report
migrate_Change_Report old =
    { reportedUser = old.reportedUser |> migrate_Id_Id migrate_Id_UserId
    , position = old.position |> migrate_Coord_Coord migrate_Units_WorldUnit
    }


migrate_Change_ServerChange : Evergreen.V91.Change.ServerChange -> Evergreen.V93.Change.ServerChange
migrate_Change_ServerChange old =
    case old of
        Evergreen.V91.Change.ServerGridChange p0 ->
            Evergreen.V93.Change.ServerGridChange
                { gridChange = p0.gridChange |> migrate_Grid_GridChange
                , newCells = p0.newCells |> List.map (migrate_Coord_Coord migrate_Units_CellUnit)
                , newCows = p0.newCows |> List.map (Tuple.mapBoth (migrate_Id_Id migrate_Id_AnimalId) migrate_Animal_Animal)
                }

        Evergreen.V91.Change.ServerUndoPoint p0 ->
            Evergreen.V93.Change.ServerUndoPoint
                { userId = p0.userId |> migrate_Id_Id migrate_Id_UserId
                , undoPoints = p0.undoPoints
                }

        Evergreen.V91.Change.ServerPickupCow p0 p1 p2 p3 ->
            Evergreen.V93.Change.ServerPickupCow (p0 |> migrate_Id_Id migrate_Id_UserId)
                (p1 |> migrate_Id_Id migrate_Id_AnimalId)
                (p2 |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit)
                p3

        Evergreen.V91.Change.ServerDropCow p0 p1 p2 ->
            Evergreen.V93.Change.ServerDropCow (p0 |> migrate_Id_Id migrate_Id_UserId)
                (p1 |> migrate_Id_Id migrate_Id_AnimalId)
                (p2 |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit)

        Evergreen.V91.Change.ServerMoveCursor p0 p1 ->
            Evergreen.V93.Change.ServerMoveCursor (p0 |> migrate_Id_Id migrate_Id_UserId)
                (p1 |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit)

        Evergreen.V91.Change.ServerUserDisconnected p0 ->
            Evergreen.V93.Change.ServerUserDisconnected (p0 |> migrate_Id_Id migrate_Id_UserId)

        Evergreen.V91.Change.ServerUserConnected p0 ->
            Evergreen.V93.Change.ServerUserConnected
                { userId = p0.userId |> migrate_Id_Id migrate_Id_UserId
                , user = p0.user |> migrate_User_FrontendUser
                , cowsSpawnedFromVisibleRegion = p0.cowsSpawnedFromVisibleRegion |> List.map (Tuple.mapBoth (migrate_Id_Id migrate_Id_AnimalId) migrate_Animal_Animal)
                }

        Evergreen.V91.Change.ServerYouLoggedIn p0 p1 ->
            Evergreen.V93.Change.ServerYouLoggedIn (p0 |> migrate_Change_LoggedIn_)
                (p1 |> migrate_User_FrontendUser)

        Evergreen.V91.Change.ServerChangeHandColor p0 p1 ->
            Evergreen.V93.Change.ServerChangeHandColor (p0 |> migrate_Id_Id migrate_Id_UserId)
                (p1 |> migrate_Color_Colors)

        Evergreen.V91.Change.ServerToggleRailSplit p0 ->
            Evergreen.V93.Change.ServerToggleRailSplit (p0 |> migrate_Coord_Coord migrate_Units_WorldUnit)

        Evergreen.V91.Change.ServerChangeDisplayName p0 p1 ->
            Evergreen.V93.Change.ServerChangeDisplayName (p0 |> migrate_Id_Id migrate_Id_UserId)
                (p1 |> migrate_DisplayName_DisplayName)

        Evergreen.V91.Change.ServerSubmitMail p0 ->
            Evergreen.V93.Change.ServerSubmitMail
                { from = p0.from |> migrate_Id_Id migrate_Id_UserId
                , to = p0.to |> migrate_Id_Id migrate_Id_UserId
                }

        Evergreen.V91.Change.ServerMailStatusChanged p0 p1 ->
            Evergreen.V93.Change.ServerMailStatusChanged (p0 |> migrate_Id_Id migrate_Id_MailId)
                (p1 |> migrate_MailEditor_MailStatus)

        Evergreen.V91.Change.ServerTeleportHomeTrainRequest p0 p1 ->
            Evergreen.V93.Change.ServerTeleportHomeTrainRequest (p0 |> migrate_Id_Id migrate_Id_TrainId) p1

        Evergreen.V91.Change.ServerLeaveHomeTrainRequest p0 p1 ->
            Evergreen.V93.Change.ServerLeaveHomeTrainRequest (p0 |> migrate_Id_Id migrate_Id_TrainId) p1

        Evergreen.V91.Change.ServerWorldUpdateBroadcast p0 ->
            Evergreen.V93.Change.ServerWorldUpdateBroadcast (p0 |> migrate_IdDict_IdDict migrate_Id_TrainId migrate_Train_TrainDiff)

        Evergreen.V91.Change.ServerReceivedMail p0 ->
            Evergreen.V93.Change.ServerReceivedMail
                { mailId = p0.mailId |> migrate_Id_Id migrate_Id_MailId
                , from = p0.from |> migrate_Id_Id migrate_Id_UserId
                , content = p0.content |> List.map migrate_MailEditor_Content
                , deliveryTime = p0.deliveryTime
                }

        Evergreen.V91.Change.ServerViewedMail p0 p1 ->
            Evergreen.V93.Change.ServerViewedMail (p0 |> migrate_Id_Id migrate_Id_MailId)
                (p1 |> migrate_Id_Id migrate_Id_UserId)

        Evergreen.V91.Change.ServerNewCows p0 ->
            Evergreen.V93.Change.ServerNewCows (p0 |> migrate_List_Nonempty_Nonempty (Tuple.mapBoth (migrate_Id_Id migrate_Id_AnimalId) migrate_Animal_Animal))

        Evergreen.V91.Change.ServerChangeTool p0 p1 ->
            Evergreen.V93.Change.ServerChangeTool (p0 |> migrate_Id_Id migrate_Id_UserId)
                (p1 |> migrate_Cursor_OtherUsersTool)

        Evergreen.V91.Change.ServerGridReadOnly p0 ->
            Evergreen.V93.Change.ServerGridReadOnly p0

        Evergreen.V91.Change.ServerVandalismReportedToAdmin p0 p1 ->
            Evergreen.V93.Change.ServerVandalismReportedToAdmin (p0 |> migrate_Id_Id migrate_Id_UserId)
                (p1 |> migrate_Change_BackendReport)

        Evergreen.V91.Change.ServerVandalismRemovedToAdmin p0 p1 ->
            Evergreen.V93.Change.ServerVandalismRemovedToAdmin (p0 |> migrate_Id_Id migrate_Id_UserId)
                (p1 |> migrate_Coord_Coord migrate_Units_WorldUnit)

        Evergreen.V91.Change.ServerSetTrainsDisabled p0 ->
            Evergreen.V93.Change.ServerSetTrainsDisabled (p0 |> migrate_Change_AreTrainsDisabled)


migrate_Change_TileHotkey : Evergreen.V91.Change.TileHotkey -> Evergreen.V93.Change.TileHotkey
migrate_Change_TileHotkey old =
    case old of
        Evergreen.V91.Change.Hotkey0 ->
            Evergreen.V93.Change.Hotkey0

        Evergreen.V91.Change.Hotkey1 ->
            Evergreen.V93.Change.Hotkey1

        Evergreen.V91.Change.Hotkey2 ->
            Evergreen.V93.Change.Hotkey2

        Evergreen.V91.Change.Hotkey3 ->
            Evergreen.V93.Change.Hotkey3

        Evergreen.V91.Change.Hotkey4 ->
            Evergreen.V93.Change.Hotkey4

        Evergreen.V91.Change.Hotkey5 ->
            Evergreen.V93.Change.Hotkey5

        Evergreen.V91.Change.Hotkey6 ->
            Evergreen.V93.Change.Hotkey6

        Evergreen.V91.Change.Hotkey7 ->
            Evergreen.V93.Change.Hotkey7

        Evergreen.V91.Change.Hotkey8 ->
            Evergreen.V93.Change.Hotkey8

        Evergreen.V91.Change.Hotkey9 ->
            Evergreen.V93.Change.Hotkey9


migrate_Change_UserStatus : Evergreen.V91.Change.UserStatus -> Evergreen.V93.Change.UserStatus
migrate_Change_UserStatus old =
    case old of
        Evergreen.V91.Change.LoggedIn p0 ->
            Evergreen.V93.Change.LoggedIn (p0 |> migrate_Change_LoggedIn_)

        Evergreen.V91.Change.NotLoggedIn p0 ->
            Evergreen.V93.Change.NotLoggedIn (p0 |> migrate_Change_NotLoggedIn_)


migrate_Color_Color : Evergreen.V91.Color.Color -> Evergreen.V93.Color.Color
migrate_Color_Color old =
    case old of
        Evergreen.V91.Color.Color p0 ->
            Evergreen.V93.Color.Color p0


migrate_Color_Colors : Evergreen.V91.Color.Colors -> Evergreen.V93.Color.Colors
migrate_Color_Colors old =
    { primaryColor = old.primaryColor |> migrate_Color_Color
    , secondaryColor = old.secondaryColor |> migrate_Color_Color
    }


migrate_Coord_Coord : (units_old -> units_new) -> Evergreen.V91.Coord.Coord units_old -> Evergreen.V93.Coord.Coord units_new
migrate_Coord_Coord migrate_units old =
    old |> Tuple.mapBoth migrate_Quantity_Quantity migrate_Quantity_Quantity


migrate_Cursor_Cursor : Evergreen.V91.Cursor.Cursor -> Evergreen.V93.Cursor.Cursor
migrate_Cursor_Cursor old =
    { position = old.position |> migrate_Point2d_Point2d migrate_Units_WorldUnit migrate_Units_WorldUnit
    , holdingCow =
        old.holdingCow
            |> Maybe.map
                (\rec ->
                    { cowId = rec.cowId |> migrate_Id_Id migrate_Id_AnimalId
                    , pickupTime = rec.pickupTime
                    }
                )
    , currentTool = old.currentTool |> migrate_Cursor_OtherUsersTool
    }


migrate_Cursor_CursorMeshes : Evergreen.V91.Cursor.CursorMeshes -> Evergreen.V93.Cursor.CursorMeshes
migrate_Cursor_CursorMeshes old =
    old


migrate_Cursor_OtherUsersTool : Evergreen.V91.Cursor.OtherUsersTool -> Evergreen.V93.Cursor.OtherUsersTool
migrate_Cursor_OtherUsersTool old =
    case old of
        Evergreen.V91.Cursor.HandTool ->
            Evergreen.V93.Cursor.HandTool

        Evergreen.V91.Cursor.TilePlacerTool ->
            Evergreen.V93.Cursor.TilePlacerTool

        Evergreen.V91.Cursor.TilePickerTool ->
            Evergreen.V93.Cursor.TilePickerTool

        Evergreen.V91.Cursor.EraserTool ->
            Evergreen.V93.Cursor.EraserTool

        Evergreen.V91.Cursor.TextTool p0 ->
            Evergreen.V93.Cursor.TextTool
                (p0
                    |> Maybe.map
                        (\rec1 ->
                            { cursorPosition = rec1.cursorPosition |> migrate_Coord_Coord migrate_Units_WorldUnit
                            }
                        )
                )

        Evergreen.V91.Cursor.ReportTool ->
            Evergreen.V93.Cursor.ReportTool


migrate_DisplayName_DisplayName : Evergreen.V91.DisplayName.DisplayName -> Evergreen.V93.DisplayName.DisplayName
migrate_DisplayName_DisplayName old =
    case old of
        Evergreen.V91.DisplayName.DisplayName p0 ->
            Evergreen.V93.DisplayName.DisplayName p0


migrate_EmailAddress_EmailAddress : Evergreen.V91.EmailAddress.EmailAddress -> Evergreen.V93.EmailAddress.EmailAddress
migrate_EmailAddress_EmailAddress old =
    case old of
        Evergreen.V91.EmailAddress.EmailAddress p0 ->
            Evergreen.V93.EmailAddress.EmailAddress p0


migrate_Geometry_Types_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V91.Geometry.Types.Point2d units_old coordinates_old -> Evergreen.V93.Geometry.Types.Point2d units_new coordinates_new
migrate_Geometry_Types_Point2d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V91.Geometry.Types.Point2d p0 ->
            Evergreen.V93.Geometry.Types.Point2d p0


migrate_GridCell_Cell : Evergreen.V91.GridCell.Cell -> Evergreen.V93.GridCell.Cell
migrate_GridCell_Cell old =
    case old of
        Evergreen.V91.GridCell.Cell p0 ->
            Evergreen.V93.GridCell.Cell
                { history = p0.history |> List.map migrate_GridCell_Value
                , undoPoint = p0.undoPoint |> migrate_IdDict_IdDict migrate_Id_UserId identity
                , cache = p0.cache |> List.map migrate_GridCell_Value
                , railSplitToggled = p0.railSplitToggled |> migrate_AssocSet_Set (migrate_Coord_Coord migrate_Units_CellLocalUnit)
                , mapCache = p0.mapCache
                }


migrate_GridCell_CellData : Evergreen.V91.GridCell.CellData -> Evergreen.V93.GridCell.CellData
migrate_GridCell_CellData old =
    case old of
        Evergreen.V91.GridCell.CellData p0 ->
            Evergreen.V93.GridCell.CellData
                { history = p0.history |> List.map migrate_GridCell_Value
                , undoPoint = p0.undoPoint |> migrate_IdDict_IdDict migrate_Id_UserId identity
                , railSplitToggled = p0.railSplitToggled |> migrate_AssocSet_Set (migrate_Coord_Coord migrate_Units_CellLocalUnit)
                , cache = p0.cache |> List.map migrate_GridCell_Value
                }


migrate_GridCell_Value : Evergreen.V91.GridCell.Value -> Evergreen.V93.GridCell.Value
migrate_GridCell_Value old =
    { userId = old.userId |> migrate_Id_Id migrate_Id_UserId
    , position = old.position |> migrate_Coord_Coord migrate_Units_CellLocalUnit
    , value = old.value |> migrate_Tile_Tile
    , colors = old.colors |> migrate_Color_Colors
    , time = Effect.Time.millisToPosix 1697325178000
    }


migrate_Grid_Grid : Evergreen.V91.Grid.Grid -> Evergreen.V93.Grid.Grid
migrate_Grid_Grid old =
    case old of
        Evergreen.V91.Grid.Grid p0 ->
            Evergreen.V93.Grid.Grid (p0 |> Dict.map (\k -> migrate_GridCell_Cell))


migrate_Grid_GridChange : Evergreen.V91.Grid.GridChange -> Evergreen.V93.Grid.GridChange
migrate_Grid_GridChange old =
    { position = old.position |> migrate_Coord_Coord migrate_Units_WorldUnit
    , change = old.change |> migrate_Tile_Tile
    , userId = old.userId |> migrate_Id_Id migrate_Id_UserId
    , colors = old.colors |> migrate_Color_Colors
    , time = Effect.Time.millisToPosix 1697325178000
    }


migrate_Grid_GridData : Evergreen.V91.Grid.GridData -> Evergreen.V93.Grid.GridData
migrate_Grid_GridData old =
    case old of
        Evergreen.V91.Grid.GridData p0 ->
            Evergreen.V93.Grid.GridData (p0 |> Dict.map (\k -> migrate_GridCell_CellData))


migrate_Grid_LocalGridChange : Evergreen.V91.Grid.LocalGridChange -> Evergreen.V93.Grid.LocalGridChange
migrate_Grid_LocalGridChange old =
    { position = old.position |> migrate_Coord_Coord migrate_Units_WorldUnit
    , change = old.change |> migrate_Tile_Tile
    , colors = old.colors |> migrate_Color_Colors
    , time = Effect.Time.millisToPosix 1697325178000
    }


migrate_IdDict_IdDict : (k_old -> k_new) -> (v_old -> v_new) -> Evergreen.V91.IdDict.IdDict k_old v_old -> Evergreen.V93.IdDict.IdDict k_new v_new
migrate_IdDict_IdDict migrate_k migrate_v old =
    case old of
        Evergreen.V91.IdDict.RBNode_elm_builtin p0 p1 p2 p3 p4 ->
            Evergreen.V93.IdDict.RBNode_elm_builtin (p0 |> migrate_IdDict_NColor)
                p1
                (p2 |> migrate_v)
                (p3 |> migrate_IdDict_IdDict migrate_k migrate_v)
                (p4 |> migrate_IdDict_IdDict migrate_k migrate_v)

        Evergreen.V91.IdDict.RBEmpty_elm_builtin ->
            Evergreen.V93.IdDict.RBEmpty_elm_builtin


migrate_IdDict_NColor : Evergreen.V91.IdDict.NColor -> Evergreen.V93.IdDict.NColor
migrate_IdDict_NColor old =
    case old of
        Evergreen.V91.IdDict.Red ->
            Evergreen.V93.IdDict.Red

        Evergreen.V91.IdDict.Black ->
            Evergreen.V93.IdDict.Black


migrate_Id_AnimalId : Evergreen.V91.Id.AnimalId -> Evergreen.V93.Id.AnimalId
migrate_Id_AnimalId old =
    case old of
        Evergreen.V91.Id.CowId p0 ->
            Evergreen.V93.Id.CowId p0


migrate_Id_EventId : Evergreen.V91.Id.EventId -> Evergreen.V93.Id.EventId
migrate_Id_EventId old =
    case old of
        Evergreen.V91.Id.EventId p0 ->
            Evergreen.V93.Id.EventId p0


migrate_Id_Id : (a_old -> a_new) -> Evergreen.V91.Id.Id a_old -> Evergreen.V93.Id.Id a_new
migrate_Id_Id migrate_a old =
    case old of
        Evergreen.V91.Id.Id p0 ->
            Evergreen.V93.Id.Id p0


migrate_Id_MailId : Evergreen.V91.Id.MailId -> Evergreen.V93.Id.MailId
migrate_Id_MailId old =
    case old of
        Evergreen.V91.Id.MailId p0 ->
            Evergreen.V93.Id.MailId p0


migrate_Id_SecretId : (a_old -> a_new) -> Evergreen.V91.Id.SecretId a_old -> Evergreen.V93.Id.SecretId a_new
migrate_Id_SecretId migrate_a old =
    case old of
        Evergreen.V91.Id.SecretId p0 ->
            Evergreen.V93.Id.SecretId p0


migrate_Id_TrainId : Evergreen.V91.Id.TrainId -> Evergreen.V93.Id.TrainId
migrate_Id_TrainId old =
    case old of
        Evergreen.V91.Id.TrainId p0 ->
            Evergreen.V93.Id.TrainId p0


migrate_Id_UserId : Evergreen.V91.Id.UserId -> Evergreen.V93.Id.UserId
migrate_Id_UserId old =
    case old of
        Evergreen.V91.Id.UserId p0 ->
            Evergreen.V93.Id.UserId p0


migrate_Keyboard_Key : Evergreen.V91.Keyboard.Key -> Evergreen.V93.Keyboard.Key
migrate_Keyboard_Key old =
    case old of
        Evergreen.V91.Keyboard.Character p0 ->
            Evergreen.V93.Keyboard.Character p0

        Evergreen.V91.Keyboard.Alt ->
            Evergreen.V93.Keyboard.Alt

        Evergreen.V91.Keyboard.AltGraph ->
            Evergreen.V93.Keyboard.AltGraph

        Evergreen.V91.Keyboard.CapsLock ->
            Evergreen.V93.Keyboard.CapsLock

        Evergreen.V91.Keyboard.Control ->
            Evergreen.V93.Keyboard.Control

        Evergreen.V91.Keyboard.Fn ->
            Evergreen.V93.Keyboard.Fn

        Evergreen.V91.Keyboard.FnLock ->
            Evergreen.V93.Keyboard.FnLock

        Evergreen.V91.Keyboard.Hyper ->
            Evergreen.V93.Keyboard.Hyper

        Evergreen.V91.Keyboard.Meta ->
            Evergreen.V93.Keyboard.Meta

        Evergreen.V91.Keyboard.NumLock ->
            Evergreen.V93.Keyboard.NumLock

        Evergreen.V91.Keyboard.ScrollLock ->
            Evergreen.V93.Keyboard.ScrollLock

        Evergreen.V91.Keyboard.Shift ->
            Evergreen.V93.Keyboard.Shift

        Evergreen.V91.Keyboard.Super ->
            Evergreen.V93.Keyboard.Super

        Evergreen.V91.Keyboard.Symbol ->
            Evergreen.V93.Keyboard.Symbol

        Evergreen.V91.Keyboard.SymbolLock ->
            Evergreen.V93.Keyboard.SymbolLock

        Evergreen.V91.Keyboard.Enter ->
            Evergreen.V93.Keyboard.Enter

        Evergreen.V91.Keyboard.Tab ->
            Evergreen.V93.Keyboard.Tab

        Evergreen.V91.Keyboard.Spacebar ->
            Evergreen.V93.Keyboard.Spacebar

        Evergreen.V91.Keyboard.ArrowDown ->
            Evergreen.V93.Keyboard.ArrowDown

        Evergreen.V91.Keyboard.ArrowLeft ->
            Evergreen.V93.Keyboard.ArrowLeft

        Evergreen.V91.Keyboard.ArrowRight ->
            Evergreen.V93.Keyboard.ArrowRight

        Evergreen.V91.Keyboard.ArrowUp ->
            Evergreen.V93.Keyboard.ArrowUp

        Evergreen.V91.Keyboard.End ->
            Evergreen.V93.Keyboard.End

        Evergreen.V91.Keyboard.Home ->
            Evergreen.V93.Keyboard.Home

        Evergreen.V91.Keyboard.PageDown ->
            Evergreen.V93.Keyboard.PageDown

        Evergreen.V91.Keyboard.PageUp ->
            Evergreen.V93.Keyboard.PageUp

        Evergreen.V91.Keyboard.Backspace ->
            Evergreen.V93.Keyboard.Backspace

        Evergreen.V91.Keyboard.Clear ->
            Evergreen.V93.Keyboard.Clear

        Evergreen.V91.Keyboard.Copy ->
            Evergreen.V93.Keyboard.Copy

        Evergreen.V91.Keyboard.CrSel ->
            Evergreen.V93.Keyboard.CrSel

        Evergreen.V91.Keyboard.Cut ->
            Evergreen.V93.Keyboard.Cut

        Evergreen.V91.Keyboard.Delete ->
            Evergreen.V93.Keyboard.Delete

        Evergreen.V91.Keyboard.EraseEof ->
            Evergreen.V93.Keyboard.EraseEof

        Evergreen.V91.Keyboard.ExSel ->
            Evergreen.V93.Keyboard.ExSel

        Evergreen.V91.Keyboard.Insert ->
            Evergreen.V93.Keyboard.Insert

        Evergreen.V91.Keyboard.Paste ->
            Evergreen.V93.Keyboard.Paste

        Evergreen.V91.Keyboard.Redo ->
            Evergreen.V93.Keyboard.Redo

        Evergreen.V91.Keyboard.Undo ->
            Evergreen.V93.Keyboard.Undo

        Evergreen.V91.Keyboard.F1 ->
            Evergreen.V93.Keyboard.F1

        Evergreen.V91.Keyboard.F2 ->
            Evergreen.V93.Keyboard.F2

        Evergreen.V91.Keyboard.F3 ->
            Evergreen.V93.Keyboard.F3

        Evergreen.V91.Keyboard.F4 ->
            Evergreen.V93.Keyboard.F4

        Evergreen.V91.Keyboard.F5 ->
            Evergreen.V93.Keyboard.F5

        Evergreen.V91.Keyboard.F6 ->
            Evergreen.V93.Keyboard.F6

        Evergreen.V91.Keyboard.F7 ->
            Evergreen.V93.Keyboard.F7

        Evergreen.V91.Keyboard.F8 ->
            Evergreen.V93.Keyboard.F8

        Evergreen.V91.Keyboard.F9 ->
            Evergreen.V93.Keyboard.F9

        Evergreen.V91.Keyboard.F10 ->
            Evergreen.V93.Keyboard.F10

        Evergreen.V91.Keyboard.F11 ->
            Evergreen.V93.Keyboard.F11

        Evergreen.V91.Keyboard.F12 ->
            Evergreen.V93.Keyboard.F12

        Evergreen.V91.Keyboard.F13 ->
            Evergreen.V93.Keyboard.F13

        Evergreen.V91.Keyboard.F14 ->
            Evergreen.V93.Keyboard.F14

        Evergreen.V91.Keyboard.F15 ->
            Evergreen.V93.Keyboard.F15

        Evergreen.V91.Keyboard.F16 ->
            Evergreen.V93.Keyboard.F16

        Evergreen.V91.Keyboard.F17 ->
            Evergreen.V93.Keyboard.F17

        Evergreen.V91.Keyboard.F18 ->
            Evergreen.V93.Keyboard.F18

        Evergreen.V91.Keyboard.F19 ->
            Evergreen.V93.Keyboard.F19

        Evergreen.V91.Keyboard.F20 ->
            Evergreen.V93.Keyboard.F20

        Evergreen.V91.Keyboard.Again ->
            Evergreen.V93.Keyboard.Again

        Evergreen.V91.Keyboard.Attn ->
            Evergreen.V93.Keyboard.Attn

        Evergreen.V91.Keyboard.Cancel ->
            Evergreen.V93.Keyboard.Cancel

        Evergreen.V91.Keyboard.ContextMenu ->
            Evergreen.V93.Keyboard.ContextMenu

        Evergreen.V91.Keyboard.Escape ->
            Evergreen.V93.Keyboard.Escape

        Evergreen.V91.Keyboard.Execute ->
            Evergreen.V93.Keyboard.Execute

        Evergreen.V91.Keyboard.Find ->
            Evergreen.V93.Keyboard.Find

        Evergreen.V91.Keyboard.Finish ->
            Evergreen.V93.Keyboard.Finish

        Evergreen.V91.Keyboard.Help ->
            Evergreen.V93.Keyboard.Help

        Evergreen.V91.Keyboard.Pause ->
            Evergreen.V93.Keyboard.Pause

        Evergreen.V91.Keyboard.Play ->
            Evergreen.V93.Keyboard.Play

        Evergreen.V91.Keyboard.Props ->
            Evergreen.V93.Keyboard.Props

        Evergreen.V91.Keyboard.Select ->
            Evergreen.V93.Keyboard.Select

        Evergreen.V91.Keyboard.ZoomIn ->
            Evergreen.V93.Keyboard.ZoomIn

        Evergreen.V91.Keyboard.ZoomOut ->
            Evergreen.V93.Keyboard.ZoomOut

        Evergreen.V91.Keyboard.AppSwitch ->
            Evergreen.V93.Keyboard.AppSwitch

        Evergreen.V91.Keyboard.Call ->
            Evergreen.V93.Keyboard.Call

        Evergreen.V91.Keyboard.Camera ->
            Evergreen.V93.Keyboard.Camera

        Evergreen.V91.Keyboard.CameraFocus ->
            Evergreen.V93.Keyboard.CameraFocus

        Evergreen.V91.Keyboard.EndCall ->
            Evergreen.V93.Keyboard.EndCall

        Evergreen.V91.Keyboard.GoBack ->
            Evergreen.V93.Keyboard.GoBack

        Evergreen.V91.Keyboard.GoHome ->
            Evergreen.V93.Keyboard.GoHome

        Evergreen.V91.Keyboard.HeadsetHook ->
            Evergreen.V93.Keyboard.HeadsetHook

        Evergreen.V91.Keyboard.LastNumberRedial ->
            Evergreen.V93.Keyboard.LastNumberRedial

        Evergreen.V91.Keyboard.Notification ->
            Evergreen.V93.Keyboard.Notification

        Evergreen.V91.Keyboard.MannerMode ->
            Evergreen.V93.Keyboard.MannerMode

        Evergreen.V91.Keyboard.VoiceDial ->
            Evergreen.V93.Keyboard.VoiceDial

        Evergreen.V91.Keyboard.ChannelDown ->
            Evergreen.V93.Keyboard.ChannelDown

        Evergreen.V91.Keyboard.ChannelUp ->
            Evergreen.V93.Keyboard.ChannelUp

        Evergreen.V91.Keyboard.MediaFastForward ->
            Evergreen.V93.Keyboard.MediaFastForward

        Evergreen.V91.Keyboard.MediaPause ->
            Evergreen.V93.Keyboard.MediaPause

        Evergreen.V91.Keyboard.MediaPlay ->
            Evergreen.V93.Keyboard.MediaPlay

        Evergreen.V91.Keyboard.MediaPlayPause ->
            Evergreen.V93.Keyboard.MediaPlayPause

        Evergreen.V91.Keyboard.MediaRecord ->
            Evergreen.V93.Keyboard.MediaRecord

        Evergreen.V91.Keyboard.MediaRewind ->
            Evergreen.V93.Keyboard.MediaRewind

        Evergreen.V91.Keyboard.MediaStop ->
            Evergreen.V93.Keyboard.MediaStop

        Evergreen.V91.Keyboard.MediaTrackNext ->
            Evergreen.V93.Keyboard.MediaTrackNext

        Evergreen.V91.Keyboard.MediaTrackPrevious ->
            Evergreen.V93.Keyboard.MediaTrackPrevious


migrate_List_Nonempty_Nonempty : (a_old -> a_new) -> List.Nonempty.Nonempty a_old -> List.Nonempty.Nonempty a_new
migrate_List_Nonempty_Nonempty migrate_a old =
    old |> List.Nonempty.map migrate_a


migrate_MailEditor_BackendMail : Evergreen.V91.MailEditor.BackendMail -> Evergreen.V93.MailEditor.BackendMail
migrate_MailEditor_BackendMail old =
    { content = old.content |> List.map migrate_MailEditor_Content
    , status = old.status |> migrate_MailEditor_MailStatus
    , from = old.from |> migrate_Id_Id migrate_Id_UserId
    , to = old.to |> migrate_Id_Id migrate_Id_UserId
    }


migrate_MailEditor_Content : Evergreen.V91.MailEditor.Content -> Evergreen.V93.MailEditor.Content
migrate_MailEditor_Content old =
    case old of
        Evergreen.V91.MailEditor.ImageType p0 p1 ->
            Evergreen.V93.MailEditor.ImageType p0 (p1 |> migrate_MailEditor_Image)

        Evergreen.V91.MailEditor.TextType p0 p1 ->
            Evergreen.V93.MailEditor.TextType p0 p1


migrate_MailEditor_EditorState : Evergreen.V91.MailEditor.EditorState -> Evergreen.V93.MailEditor.EditorState
migrate_MailEditor_EditorState old =
    { content = old.content |> List.map migrate_MailEditor_Content
    }


migrate_MailEditor_FrontendMail : Evergreen.V91.MailEditor.FrontendMail -> Evergreen.V93.MailEditor.FrontendMail
migrate_MailEditor_FrontendMail old =
    { status = old.status |> migrate_MailEditor_MailStatus
    , from = old.from |> migrate_Id_Id migrate_Id_UserId
    , to = old.to |> migrate_Id_Id migrate_Id_UserId
    }


migrate_MailEditor_Hover : Evergreen.V91.MailEditor.Hover -> Evergreen.V93.MailEditor.Hover
migrate_MailEditor_Hover old =
    case old of
        Evergreen.V91.MailEditor.BackgroundHover ->
            Evergreen.V93.MailEditor.BackgroundHover

        Evergreen.V91.MailEditor.ImageButton p0 ->
            Evergreen.V93.MailEditor.ImageButton p0

        Evergreen.V91.MailEditor.MailButton ->
            Evergreen.V93.MailEditor.MailButton

        Evergreen.V91.MailEditor.EraserButton ->
            Evergreen.V93.MailEditor.EraserButton

        Evergreen.V91.MailEditor.SendLetterButton ->
            Evergreen.V93.MailEditor.SendLetterButton

        Evergreen.V91.MailEditor.CloseSendLetterInstructionsButton ->
            Evergreen.V93.MailEditor.CloseSendLetterInstructionsButton

        Evergreen.V91.MailEditor.InboxRowButton p0 ->
            Evergreen.V93.MailEditor.InboxRowButton (p0 |> migrate_Id_Id migrate_Id_MailId)

        Evergreen.V91.MailEditor.TextToolButton ->
            Evergreen.V93.MailEditor.TextToolButton

        Evergreen.V91.MailEditor.ExportButton ->
            Evergreen.V93.MailEditor.ExportButton

        Evergreen.V91.MailEditor.ImportButton ->
            Evergreen.V93.MailEditor.ImportButton

        Evergreen.V91.MailEditor.CloseMailViewButton ->
            Evergreen.V93.MailEditor.CloseMailViewButton


migrate_MailEditor_Image : Evergreen.V91.MailEditor.Image -> Evergreen.V93.MailEditor.Image
migrate_MailEditor_Image old =
    case old of
        Evergreen.V91.MailEditor.Stamp p0 ->
            Evergreen.V93.MailEditor.Stamp (p0 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.SunglassesEmoji p0 ->
            Evergreen.V93.MailEditor.SunglassesEmoji (p0 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.NormalEmoji p0 ->
            Evergreen.V93.MailEditor.NormalEmoji (p0 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.SadEmoji p0 ->
            Evergreen.V93.MailEditor.SadEmoji (p0 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.Man p0 ->
            Evergreen.V93.MailEditor.Man (p0 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.TileImage p0 p1 p2 ->
            Evergreen.V93.MailEditor.TileImage (p0 |> migrate_Tile_TileGroup)
                p1
                (p2 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.Grass ->
            Evergreen.V93.MailEditor.Grass

        Evergreen.V91.MailEditor.DefaultCursor p0 ->
            Evergreen.V93.MailEditor.DefaultCursor (p0 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.DragCursor p0 ->
            Evergreen.V93.MailEditor.DragCursor (p0 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.PinchCursor p0 ->
            Evergreen.V93.MailEditor.PinchCursor (p0 |> migrate_Color_Colors)

        Evergreen.V91.MailEditor.Line p0 p1 ->
            Evergreen.V93.MailEditor.Line p0 (p1 |> migrate_Color_Color)

        Evergreen.V91.MailEditor.Animal p0 p1 ->
            Evergreen.V93.MailEditor.Animal (p0 |> migrate_Animal_AnimalType)
                (p1 |> migrate_Color_Colors)


migrate_MailEditor_MailStatus : Evergreen.V91.MailEditor.MailStatus -> Evergreen.V93.MailEditor.MailStatus
migrate_MailEditor_MailStatus old =
    case old of
        Evergreen.V91.MailEditor.MailWaitingPickup ->
            Evergreen.V93.MailEditor.MailWaitingPickup

        Evergreen.V91.MailEditor.MailInTransit p0 ->
            Evergreen.V93.MailEditor.MailInTransit (p0 |> migrate_Id_Id migrate_Id_TrainId)

        Evergreen.V91.MailEditor.MailReceived p0 ->
            Evergreen.V93.MailEditor.MailReceived p0

        Evergreen.V91.MailEditor.MailReceivedAndViewed p0 ->
            Evergreen.V93.MailEditor.MailReceivedAndViewed p0

        Evergreen.V91.MailEditor.MailDeletedByAdmin p0 ->
            Evergreen.V93.MailEditor.MailDeletedByAdmin
                { previousStatus = p0.previousStatus |> migrate_MailEditor_MailStatus2
                , deletedAt = p0.deletedAt
                }


migrate_MailEditor_MailStatus2 : Evergreen.V91.MailEditor.MailStatus2 -> Evergreen.V93.MailEditor.MailStatus2
migrate_MailEditor_MailStatus2 old =
    case old of
        Evergreen.V91.MailEditor.MailWaitingPickup2 ->
            Evergreen.V93.MailEditor.MailWaitingPickup2

        Evergreen.V91.MailEditor.MailInTransit2 p0 ->
            Evergreen.V93.MailEditor.MailInTransit2 (p0 |> migrate_Id_Id migrate_Id_TrainId)

        Evergreen.V91.MailEditor.MailReceived2 p0 ->
            Evergreen.V93.MailEditor.MailReceived2 p0

        Evergreen.V91.MailEditor.MailReceivedAndViewed2 p0 ->
            Evergreen.V93.MailEditor.MailReceivedAndViewed2 p0


migrate_MailEditor_ReceivedMail : Evergreen.V91.MailEditor.ReceivedMail -> Evergreen.V93.MailEditor.ReceivedMail
migrate_MailEditor_ReceivedMail old =
    { content = old.content |> List.map migrate_MailEditor_Content
    , isViewed = old.isViewed
    , from = old.from |> migrate_Id_Id migrate_Id_UserId
    , deliveryTime = old.deliveryTime
    }


migrate_Point2d_Point2d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V91.Point2d.Point2d units_old coordinates_old -> Evergreen.V93.Point2d.Point2d units_new coordinates_new
migrate_Point2d_Point2d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Point2d migrate_units migrate_coordinates


migrate_Postmark_PostmarkSendResponse : Evergreen.V91.Postmark.PostmarkSendResponse -> Evergreen.V93.Postmark.PostmarkSendResponse
migrate_Postmark_PostmarkSendResponse old =
    old


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_Route_InviteToken : Evergreen.V91.Route.InviteToken -> Evergreen.V93.Route.InviteToken
migrate_Route_InviteToken old =
    case old of
        Evergreen.V91.Route.InviteToken p0 ->
            Evergreen.V93.Route.InviteToken p0


migrate_Route_LoginOrInviteToken : Evergreen.V91.Route.LoginOrInviteToken -> Evergreen.V93.Route.LoginOrInviteToken
migrate_Route_LoginOrInviteToken old =
    case old of
        Evergreen.V91.Route.LoginToken2 p0 ->
            Evergreen.V93.Route.LoginToken2 (p0 |> migrate_Id_SecretId migrate_Route_LoginToken)

        Evergreen.V91.Route.InviteToken2 p0 ->
            Evergreen.V93.Route.InviteToken2 (p0 |> migrate_Id_SecretId migrate_Route_InviteToken)


migrate_Route_LoginToken : Evergreen.V91.Route.LoginToken -> Evergreen.V93.Route.LoginToken
migrate_Route_LoginToken old =
    case old of
        Evergreen.V91.Route.LoginToken p0 ->
            Evergreen.V93.Route.LoginToken p0


migrate_TextInput_State : Evergreen.V91.TextInput.State -> Evergreen.V93.TextInput.State
migrate_TextInput_State old =
    old


migrate_Tile_Category : Evergreen.V91.Tile.Category -> Evergreen.V93.Tile.Category
migrate_Tile_Category old =
    case old of
        Evergreen.V91.Tile.Scenery ->
            Evergreen.V93.Tile.Scenery

        Evergreen.V91.Tile.Buildings ->
            Evergreen.V93.Tile.Buildings

        Evergreen.V91.Tile.Rail ->
            Evergreen.V93.Tile.Rail

        Evergreen.V91.Tile.Road ->
            Evergreen.V93.Tile.Road


migrate_Tile_RailPath : Evergreen.V91.Tile.RailPath -> Evergreen.V93.Tile.RailPath
migrate_Tile_RailPath old =
    case old of
        Evergreen.V91.Tile.RailPathHorizontal p0 ->
            Evergreen.V93.Tile.RailPathHorizontal p0

        Evergreen.V91.Tile.RailPathVertical p0 ->
            Evergreen.V93.Tile.RailPathVertical p0

        Evergreen.V91.Tile.RailPathBottomToRight ->
            Evergreen.V93.Tile.RailPathBottomToRight

        Evergreen.V91.Tile.RailPathBottomToLeft ->
            Evergreen.V93.Tile.RailPathBottomToLeft

        Evergreen.V91.Tile.RailPathTopToRight ->
            Evergreen.V93.Tile.RailPathTopToRight

        Evergreen.V91.Tile.RailPathTopToLeft ->
            Evergreen.V93.Tile.RailPathTopToLeft

        Evergreen.V91.Tile.RailPathBottomToRightLarge ->
            Evergreen.V93.Tile.RailPathBottomToRightLarge

        Evergreen.V91.Tile.RailPathBottomToLeftLarge ->
            Evergreen.V93.Tile.RailPathBottomToLeftLarge

        Evergreen.V91.Tile.RailPathTopToRightLarge ->
            Evergreen.V93.Tile.RailPathTopToRightLarge

        Evergreen.V91.Tile.RailPathTopToLeftLarge ->
            Evergreen.V93.Tile.RailPathTopToLeftLarge

        Evergreen.V91.Tile.RailPathStrafeDown ->
            Evergreen.V93.Tile.RailPathStrafeDown

        Evergreen.V91.Tile.RailPathStrafeUp ->
            Evergreen.V93.Tile.RailPathStrafeUp

        Evergreen.V91.Tile.RailPathStrafeLeft ->
            Evergreen.V93.Tile.RailPathStrafeLeft

        Evergreen.V91.Tile.RailPathStrafeRight ->
            Evergreen.V93.Tile.RailPathStrafeRight

        Evergreen.V91.Tile.RailPathStrafeDownSmall ->
            Evergreen.V93.Tile.RailPathStrafeDownSmall

        Evergreen.V91.Tile.RailPathStrafeUpSmall ->
            Evergreen.V93.Tile.RailPathStrafeUpSmall

        Evergreen.V91.Tile.RailPathStrafeLeftSmall ->
            Evergreen.V93.Tile.RailPathStrafeLeftSmall

        Evergreen.V91.Tile.RailPathStrafeRightSmall ->
            Evergreen.V93.Tile.RailPathStrafeRightSmall


migrate_Tile_Tile : Evergreen.V91.Tile.Tile -> Evergreen.V93.Tile.Tile
migrate_Tile_Tile old =
    case old of
        Evergreen.V91.Tile.EmptyTile ->
            Evergreen.V93.Tile.EmptyTile

        Evergreen.V91.Tile.HouseDown ->
            Evergreen.V93.Tile.HouseDown

        Evergreen.V91.Tile.HouseRight ->
            Evergreen.V93.Tile.HouseRight

        Evergreen.V91.Tile.HouseUp ->
            Evergreen.V93.Tile.HouseUp

        Evergreen.V91.Tile.HouseLeft ->
            Evergreen.V93.Tile.HouseLeft

        Evergreen.V91.Tile.RailHorizontal ->
            Evergreen.V93.Tile.RailHorizontal

        Evergreen.V91.Tile.RailVertical ->
            Evergreen.V93.Tile.RailVertical

        Evergreen.V91.Tile.RailBottomToRight ->
            Evergreen.V93.Tile.RailBottomToRight

        Evergreen.V91.Tile.RailBottomToLeft ->
            Evergreen.V93.Tile.RailBottomToLeft

        Evergreen.V91.Tile.RailTopToRight ->
            Evergreen.V93.Tile.RailTopToRight

        Evergreen.V91.Tile.RailTopToLeft ->
            Evergreen.V93.Tile.RailTopToLeft

        Evergreen.V91.Tile.RailBottomToRightLarge ->
            Evergreen.V93.Tile.RailBottomToRightLarge

        Evergreen.V91.Tile.RailBottomToLeftLarge ->
            Evergreen.V93.Tile.RailBottomToLeftLarge

        Evergreen.V91.Tile.RailTopToRightLarge ->
            Evergreen.V93.Tile.RailTopToRightLarge

        Evergreen.V91.Tile.RailTopToLeftLarge ->
            Evergreen.V93.Tile.RailTopToLeftLarge

        Evergreen.V91.Tile.RailCrossing ->
            Evergreen.V93.Tile.RailCrossing

        Evergreen.V91.Tile.RailStrafeDown ->
            Evergreen.V93.Tile.RailStrafeDown

        Evergreen.V91.Tile.RailStrafeUp ->
            Evergreen.V93.Tile.RailStrafeUp

        Evergreen.V91.Tile.RailStrafeLeft ->
            Evergreen.V93.Tile.RailStrafeLeft

        Evergreen.V91.Tile.RailStrafeRight ->
            Evergreen.V93.Tile.RailStrafeRight

        Evergreen.V91.Tile.TrainHouseRight ->
            Evergreen.V93.Tile.TrainHouseRight

        Evergreen.V91.Tile.TrainHouseLeft ->
            Evergreen.V93.Tile.TrainHouseLeft

        Evergreen.V91.Tile.RailStrafeDownSmall ->
            Evergreen.V93.Tile.RailStrafeDownSmall

        Evergreen.V91.Tile.RailStrafeUpSmall ->
            Evergreen.V93.Tile.RailStrafeUpSmall

        Evergreen.V91.Tile.RailStrafeLeftSmall ->
            Evergreen.V93.Tile.RailStrafeLeftSmall

        Evergreen.V91.Tile.RailStrafeRightSmall ->
            Evergreen.V93.Tile.RailStrafeRightSmall

        Evergreen.V91.Tile.Sidewalk ->
            Evergreen.V93.Tile.Sidewalk

        Evergreen.V91.Tile.SidewalkHorizontalRailCrossing ->
            Evergreen.V93.Tile.SidewalkHorizontalRailCrossing

        Evergreen.V91.Tile.SidewalkVerticalRailCrossing ->
            Evergreen.V93.Tile.SidewalkVerticalRailCrossing

        Evergreen.V91.Tile.RailBottomToRight_SplitLeft ->
            Evergreen.V93.Tile.RailBottomToRight_SplitLeft

        Evergreen.V91.Tile.RailBottomToLeft_SplitUp ->
            Evergreen.V93.Tile.RailBottomToLeft_SplitUp

        Evergreen.V91.Tile.RailTopToRight_SplitDown ->
            Evergreen.V93.Tile.RailTopToRight_SplitDown

        Evergreen.V91.Tile.RailTopToLeft_SplitRight ->
            Evergreen.V93.Tile.RailTopToLeft_SplitRight

        Evergreen.V91.Tile.RailBottomToRight_SplitUp ->
            Evergreen.V93.Tile.RailBottomToRight_SplitUp

        Evergreen.V91.Tile.RailBottomToLeft_SplitRight ->
            Evergreen.V93.Tile.RailBottomToLeft_SplitRight

        Evergreen.V91.Tile.RailTopToRight_SplitLeft ->
            Evergreen.V93.Tile.RailTopToRight_SplitLeft

        Evergreen.V91.Tile.RailTopToLeft_SplitDown ->
            Evergreen.V93.Tile.RailTopToLeft_SplitDown

        Evergreen.V91.Tile.PostOffice ->
            Evergreen.V93.Tile.PostOffice

        Evergreen.V91.Tile.MowedGrass1 ->
            Evergreen.V93.Tile.MowedGrass1

        Evergreen.V91.Tile.MowedGrass4 ->
            Evergreen.V93.Tile.MowedGrass4

        Evergreen.V91.Tile.PineTree1 ->
            Evergreen.V93.Tile.PineTree1

        Evergreen.V91.Tile.PineTree2 ->
            Evergreen.V93.Tile.PineTree2

        Evergreen.V91.Tile.BigPineTree ->
            Evergreen.V93.Tile.BigPineTree

        Evergreen.V91.Tile.LogCabinDown ->
            Evergreen.V93.Tile.LogCabinDown

        Evergreen.V91.Tile.LogCabinRight ->
            Evergreen.V93.Tile.LogCabinRight

        Evergreen.V91.Tile.LogCabinUp ->
            Evergreen.V93.Tile.LogCabinUp

        Evergreen.V91.Tile.LogCabinLeft ->
            Evergreen.V93.Tile.LogCabinLeft

        Evergreen.V91.Tile.RoadHorizontal ->
            Evergreen.V93.Tile.RoadHorizontal

        Evergreen.V91.Tile.RoadVertical ->
            Evergreen.V93.Tile.RoadVertical

        Evergreen.V91.Tile.RoadBottomToLeft ->
            Evergreen.V93.Tile.RoadBottomToLeft

        Evergreen.V91.Tile.RoadTopToLeft ->
            Evergreen.V93.Tile.RoadTopToLeft

        Evergreen.V91.Tile.RoadTopToRight ->
            Evergreen.V93.Tile.RoadTopToRight

        Evergreen.V91.Tile.RoadBottomToRight ->
            Evergreen.V93.Tile.RoadBottomToRight

        Evergreen.V91.Tile.Road4Way ->
            Evergreen.V93.Tile.Road4Way

        Evergreen.V91.Tile.RoadSidewalkCrossingHorizontal ->
            Evergreen.V93.Tile.RoadSidewalkCrossingHorizontal

        Evergreen.V91.Tile.RoadSidewalkCrossingVertical ->
            Evergreen.V93.Tile.RoadSidewalkCrossingVertical

        Evergreen.V91.Tile.Road3WayDown ->
            Evergreen.V93.Tile.Road3WayDown

        Evergreen.V91.Tile.Road3WayLeft ->
            Evergreen.V93.Tile.Road3WayLeft

        Evergreen.V91.Tile.Road3WayUp ->
            Evergreen.V93.Tile.Road3WayUp

        Evergreen.V91.Tile.Road3WayRight ->
            Evergreen.V93.Tile.Road3WayRight

        Evergreen.V91.Tile.RoadRailCrossingHorizontal ->
            Evergreen.V93.Tile.RoadRailCrossingHorizontal

        Evergreen.V91.Tile.RoadRailCrossingVertical ->
            Evergreen.V93.Tile.RoadRailCrossingVertical

        Evergreen.V91.Tile.FenceHorizontal ->
            Evergreen.V93.Tile.FenceHorizontal

        Evergreen.V91.Tile.FenceVertical ->
            Evergreen.V93.Tile.FenceVertical

        Evergreen.V91.Tile.FenceDiagonal ->
            Evergreen.V93.Tile.FenceDiagonal

        Evergreen.V91.Tile.FenceAntidiagonal ->
            Evergreen.V93.Tile.FenceAntidiagonal

        Evergreen.V91.Tile.RoadDeadendUp ->
            Evergreen.V93.Tile.RoadDeadendUp

        Evergreen.V91.Tile.RoadDeadendDown ->
            Evergreen.V93.Tile.RoadDeadendDown

        Evergreen.V91.Tile.BusStopDown ->
            Evergreen.V93.Tile.BusStopDown

        Evergreen.V91.Tile.BusStopLeft ->
            Evergreen.V93.Tile.BusStopLeft

        Evergreen.V91.Tile.BusStopRight ->
            Evergreen.V93.Tile.BusStopRight

        Evergreen.V91.Tile.BusStopUp ->
            Evergreen.V93.Tile.BusStopUp

        Evergreen.V91.Tile.Hospital ->
            Evergreen.V93.Tile.Hospital

        Evergreen.V91.Tile.Statue ->
            Evergreen.V93.Tile.Statue

        Evergreen.V91.Tile.HedgeRowDown ->
            Evergreen.V93.Tile.HedgeRowDown

        Evergreen.V91.Tile.HedgeRowLeft ->
            Evergreen.V93.Tile.HedgeRowLeft

        Evergreen.V91.Tile.HedgeRowRight ->
            Evergreen.V93.Tile.HedgeRowRight

        Evergreen.V91.Tile.HedgeRowUp ->
            Evergreen.V93.Tile.HedgeRowUp

        Evergreen.V91.Tile.HedgeCornerDownLeft ->
            Evergreen.V93.Tile.HedgeCornerDownLeft

        Evergreen.V91.Tile.HedgeCornerDownRight ->
            Evergreen.V93.Tile.HedgeCornerDownRight

        Evergreen.V91.Tile.HedgeCornerUpLeft ->
            Evergreen.V93.Tile.HedgeCornerUpLeft

        Evergreen.V91.Tile.HedgeCornerUpRight ->
            Evergreen.V93.Tile.HedgeCornerUpRight

        Evergreen.V91.Tile.HedgePillarDownLeft ->
            Evergreen.V93.Tile.HedgePillarDownLeft

        Evergreen.V91.Tile.HedgePillarDownRight ->
            Evergreen.V93.Tile.HedgePillarDownRight

        Evergreen.V91.Tile.HedgePillarUpLeft ->
            Evergreen.V93.Tile.HedgePillarUpLeft

        Evergreen.V91.Tile.HedgePillarUpRight ->
            Evergreen.V93.Tile.HedgePillarUpRight

        Evergreen.V91.Tile.ApartmentDown ->
            Evergreen.V93.Tile.ApartmentDown

        Evergreen.V91.Tile.ApartmentLeft ->
            Evergreen.V93.Tile.ApartmentLeft

        Evergreen.V91.Tile.ApartmentRight ->
            Evergreen.V93.Tile.ApartmentRight

        Evergreen.V91.Tile.ApartmentUp ->
            Evergreen.V93.Tile.ApartmentUp

        Evergreen.V91.Tile.RockDown ->
            Evergreen.V93.Tile.RockDown

        Evergreen.V91.Tile.RockLeft ->
            Evergreen.V93.Tile.RockLeft

        Evergreen.V91.Tile.RockRight ->
            Evergreen.V93.Tile.RockRight

        Evergreen.V91.Tile.RockUp ->
            Evergreen.V93.Tile.RockUp

        Evergreen.V91.Tile.Flowers1 ->
            Evergreen.V93.Tile.Flowers1

        Evergreen.V91.Tile.Flowers2 ->
            Evergreen.V93.Tile.Flowers2

        Evergreen.V91.Tile.ElmTree ->
            Evergreen.V93.Tile.ElmTree

        Evergreen.V91.Tile.DirtPathHorizontal ->
            Evergreen.V93.Tile.DirtPathHorizontal

        Evergreen.V91.Tile.DirtPathVertical ->
            Evergreen.V93.Tile.DirtPathVertical

        Evergreen.V91.Tile.BigText p0 ->
            Evergreen.V93.Tile.BigText p0

        Evergreen.V91.Tile.Hyperlink ->
            Evergreen.V93.Tile.Hyperlink

        Evergreen.V91.Tile.BenchDown ->
            Evergreen.V93.Tile.BenchDown

        Evergreen.V91.Tile.BenchLeft ->
            Evergreen.V93.Tile.BenchLeft

        Evergreen.V91.Tile.BenchUp ->
            Evergreen.V93.Tile.BenchUp

        Evergreen.V91.Tile.BenchRight ->
            Evergreen.V93.Tile.BenchRight

        Evergreen.V91.Tile.ParkingDown ->
            Evergreen.V93.Tile.ParkingDown

        Evergreen.V91.Tile.ParkingLeft ->
            Evergreen.V93.Tile.ParkingLeft

        Evergreen.V91.Tile.ParkingUp ->
            Evergreen.V93.Tile.ParkingUp

        Evergreen.V91.Tile.ParkingRight ->
            Evergreen.V93.Tile.ParkingRight

        Evergreen.V91.Tile.ParkingRoad ->
            Evergreen.V93.Tile.ParkingRoad

        Evergreen.V91.Tile.ParkingRoundabout ->
            Evergreen.V93.Tile.ParkingRoundabout

        Evergreen.V91.Tile.CornerHouseUpLeft ->
            Evergreen.V93.Tile.CornerHouseUpLeft

        Evergreen.V91.Tile.CornerHouseUpRight ->
            Evergreen.V93.Tile.CornerHouseUpRight

        Evergreen.V91.Tile.CornerHouseDownLeft ->
            Evergreen.V93.Tile.CornerHouseDownLeft

        Evergreen.V91.Tile.CornerHouseDownRight ->
            Evergreen.V93.Tile.CornerHouseDownRight

        Evergreen.V91.Tile.DogHouseDown ->
            Evergreen.V93.Tile.DogHouseDown

        Evergreen.V91.Tile.DogHouseRight ->
            Evergreen.V93.Tile.DogHouseRight

        Evergreen.V91.Tile.DogHouseUp ->
            Evergreen.V93.Tile.DogHouseUp

        Evergreen.V91.Tile.DogHouseLeft ->
            Evergreen.V93.Tile.DogHouseLeft

        Evergreen.V91.Tile.Mushroom ->
            Evergreen.V93.Tile.Mushroom

        Evergreen.V91.Tile.TreeStump1 ->
            Evergreen.V93.Tile.TreeStump1

        Evergreen.V91.Tile.TreeStump2 ->
            Evergreen.V93.Tile.TreeStump2

        Evergreen.V91.Tile.Sunflowers ->
            Evergreen.V93.Tile.Sunflowers

        Evergreen.V91.Tile.RailDeadEndLeft ->
            Evergreen.V93.Tile.RailDeadEndLeft

        Evergreen.V91.Tile.RailDeadEndRight ->
            Evergreen.V93.Tile.RailDeadEndRight

        Evergreen.V91.Tile.RailStrafeLeftToRight_SplitUp ->
            Evergreen.V93.Tile.RailStrafeLeftToRight_SplitUp

        Evergreen.V91.Tile.RailStrafeLeftToRight_SplitDown ->
            Evergreen.V93.Tile.RailStrafeLeftToRight_SplitDown

        Evergreen.V91.Tile.RailStrafeRightToLeft_SplitUp ->
            Evergreen.V93.Tile.RailStrafeRightToLeft_SplitUp

        Evergreen.V91.Tile.RailStrafeRightToLeft_SplitDown ->
            Evergreen.V93.Tile.RailStrafeRightToLeft_SplitDown

        Evergreen.V91.Tile.RailStrafeTopToBottom_SplitLeft ->
            Evergreen.V93.Tile.RailStrafeTopToBottom_SplitLeft

        Evergreen.V91.Tile.RailStrafeTopToBottom_SplitRight ->
            Evergreen.V93.Tile.RailStrafeTopToBottom_SplitRight

        Evergreen.V91.Tile.RailStrafeBottomToTop_SplitLeft ->
            Evergreen.V93.Tile.RailStrafeBottomToTop_SplitLeft

        Evergreen.V91.Tile.RailStrafeBottomToTop_SplitRight ->
            Evergreen.V93.Tile.RailStrafeBottomToTop_SplitRight

        Evergreen.V91.Tile.RoadManholeDown ->
            Evergreen.V93.Tile.RoadManholeDown

        Evergreen.V91.Tile.RoadManholeLeft ->
            Evergreen.V93.Tile.RoadManholeLeft

        Evergreen.V91.Tile.RoadManholeUp ->
            Evergreen.V93.Tile.RoadManholeUp

        Evergreen.V91.Tile.RoadManholeRight ->
            Evergreen.V93.Tile.RoadManholeRight


migrate_Tile_TileGroup : Evergreen.V91.Tile.TileGroup -> Evergreen.V93.Tile.TileGroup
migrate_Tile_TileGroup old =
    case old of
        Evergreen.V91.Tile.EmptyTileGroup ->
            Evergreen.V93.Tile.EmptyTileGroup

        Evergreen.V91.Tile.HouseGroup ->
            Evergreen.V93.Tile.HouseGroup

        Evergreen.V91.Tile.RailStraightGroup ->
            Evergreen.V93.Tile.RailStraightGroup

        Evergreen.V91.Tile.RailTurnGroup ->
            Evergreen.V93.Tile.RailTurnGroup

        Evergreen.V91.Tile.RailTurnLargeGroup ->
            Evergreen.V93.Tile.RailTurnLargeGroup

        Evergreen.V91.Tile.RailStrafeGroup ->
            Evergreen.V93.Tile.RailStrafeGroup

        Evergreen.V91.Tile.RailStrafeSmallGroup ->
            Evergreen.V93.Tile.RailStrafeSmallGroup

        Evergreen.V91.Tile.RailCrossingGroup ->
            Evergreen.V93.Tile.RailCrossingGroup

        Evergreen.V91.Tile.TrainHouseGroup ->
            Evergreen.V93.Tile.TrainHouseGroup

        Evergreen.V91.Tile.SidewalkGroup ->
            Evergreen.V93.Tile.SidewalkGroup

        Evergreen.V91.Tile.SidewalkRailGroup ->
            Evergreen.V93.Tile.SidewalkRailGroup

        Evergreen.V91.Tile.RailTurnSplitGroup ->
            Evergreen.V93.Tile.RailTurnSplitGroup

        Evergreen.V91.Tile.RailTurnSplitMirrorGroup ->
            Evergreen.V93.Tile.RailTurnSplitMirrorGroup

        Evergreen.V91.Tile.PostOfficeGroup ->
            Evergreen.V93.Tile.PostOfficeGroup

        Evergreen.V91.Tile.PineTreeGroup ->
            Evergreen.V93.Tile.PineTreeGroup

        Evergreen.V91.Tile.BigPineTreeGroup ->
            Evergreen.V93.Tile.BigPineTreeGroup

        Evergreen.V91.Tile.LogCabinGroup ->
            Evergreen.V93.Tile.LogCabinGroup

        Evergreen.V91.Tile.RoadStraightGroup ->
            Evergreen.V93.Tile.RoadStraightGroup

        Evergreen.V91.Tile.RoadTurnGroup ->
            Evergreen.V93.Tile.RoadTurnGroup

        Evergreen.V91.Tile.Road4WayGroup ->
            Evergreen.V93.Tile.Road4WayGroup

        Evergreen.V91.Tile.RoadSidewalkCrossingGroup ->
            Evergreen.V93.Tile.RoadSidewalkCrossingGroup

        Evergreen.V91.Tile.Road3WayGroup ->
            Evergreen.V93.Tile.Road3WayGroup

        Evergreen.V91.Tile.RoadRailCrossingGroup ->
            Evergreen.V93.Tile.RoadRailCrossingGroup

        Evergreen.V91.Tile.RoadDeadendGroup ->
            Evergreen.V93.Tile.RoadDeadendGroup

        Evergreen.V91.Tile.FenceStraightGroup ->
            Evergreen.V93.Tile.FenceStraightGroup

        Evergreen.V91.Tile.BusStopGroup ->
            Evergreen.V93.Tile.BusStopGroup

        Evergreen.V91.Tile.HospitalGroup ->
            Evergreen.V93.Tile.HospitalGroup

        Evergreen.V91.Tile.StatueGroup ->
            Evergreen.V93.Tile.StatueGroup

        Evergreen.V91.Tile.HedgeRowGroup ->
            Evergreen.V93.Tile.HedgeRowGroup

        Evergreen.V91.Tile.HedgeCornerGroup ->
            Evergreen.V93.Tile.HedgeCornerGroup

        Evergreen.V91.Tile.HedgePillarGroup ->
            Evergreen.V93.Tile.HedgePillarGroup

        Evergreen.V91.Tile.ApartmentGroup ->
            Evergreen.V93.Tile.ApartmentGroup

        Evergreen.V91.Tile.RockGroup ->
            Evergreen.V93.Tile.RockGroup

        Evergreen.V91.Tile.FlowersGroup ->
            Evergreen.V93.Tile.FlowersGroup

        Evergreen.V91.Tile.ElmTreeGroup ->
            Evergreen.V93.Tile.ElmTreeGroup

        Evergreen.V91.Tile.DirtPathGroup ->
            Evergreen.V93.Tile.DirtPathGroup

        Evergreen.V91.Tile.BigTextGroup ->
            Evergreen.V93.Tile.BigTextGroup

        Evergreen.V91.Tile.HyperlinkGroup ->
            Evergreen.V93.Tile.HyperlinkGroup

        Evergreen.V91.Tile.BenchGroup ->
            Evergreen.V93.Tile.BenchGroup

        Evergreen.V91.Tile.ParkingLotGroup ->
            Evergreen.V93.Tile.ParkingLotGroup

        Evergreen.V91.Tile.ParkingRoadGroup ->
            Evergreen.V93.Tile.ParkingRoadGroup

        Evergreen.V91.Tile.ParkingRoundaboutGroup ->
            Evergreen.V93.Tile.ParkingRoundaboutGroup

        Evergreen.V91.Tile.CornerHouseGroup ->
            Evergreen.V93.Tile.CornerHouseGroup

        Evergreen.V91.Tile.DogHouseGroup ->
            Evergreen.V93.Tile.DogHouseGroup

        Evergreen.V91.Tile.MushroomGroup ->
            Evergreen.V93.Tile.MushroomGroup

        Evergreen.V91.Tile.TreeStumpGroup ->
            Evergreen.V93.Tile.TreeStumpGroup

        Evergreen.V91.Tile.SunflowersGroup ->
            Evergreen.V93.Tile.SunflowersGroup

        Evergreen.V91.Tile.RailDeadendGroup ->
            Evergreen.V93.Tile.RailDeadendGroup

        Evergreen.V91.Tile.RailStrafeSplitGroup ->
            Evergreen.V93.Tile.RailStrafeSplitGroup

        Evergreen.V91.Tile.RailStrafeSplitMirrorGroup ->
            Evergreen.V93.Tile.RailStrafeSplitMirrorGroup

        Evergreen.V91.Tile.RoadStraightManholeGroup ->
            Evergreen.V93.Tile.RoadStraightManholeGroup


migrate_TimeOfDay_TimeOfDay : Evergreen.V91.Change.TimeOfDay -> Evergreen.V93.TimeOfDay.TimeOfDay
migrate_TimeOfDay_TimeOfDay old =
    case old of
        Evergreen.V91.Change.Automatic ->
            Evergreen.V93.TimeOfDay.Automatic

        Evergreen.V91.Change.AlwaysDay ->
            Evergreen.V93.TimeOfDay.AlwaysDay

        Evergreen.V91.Change.AlwaysNight ->
            Evergreen.V93.TimeOfDay.AlwaysNight


migrate_Train_FieldChanged : (a_old -> a_new) -> Evergreen.V91.Train.FieldChanged a_old -> Evergreen.V93.Train.FieldChanged a_new
migrate_Train_FieldChanged migrate_a old =
    case old of
        Evergreen.V91.Train.FieldChanged p0 ->
            Evergreen.V93.Train.FieldChanged (p0 |> migrate_a)

        Evergreen.V91.Train.Unchanged ->
            Evergreen.V93.Train.Unchanged


migrate_Train_IsStuckOrDerailed : Evergreen.V91.Train.IsStuckOrDerailed -> Evergreen.V93.Train.IsStuckOrDerailed
migrate_Train_IsStuckOrDerailed old =
    case old of
        Evergreen.V91.Train.IsStuck p0 ->
            Evergreen.V93.Train.IsStuck p0

        Evergreen.V91.Train.IsDerailed p0 p1 ->
            Evergreen.V93.Train.IsDerailed p0 (p1 |> migrate_Id_Id migrate_Id_TrainId)

        Evergreen.V91.Train.IsNotStuckOrDerailed ->
            Evergreen.V93.Train.IsNotStuckOrDerailed


migrate_Train_PreviousPath : Evergreen.V91.Train.PreviousPath -> Evergreen.V93.Train.PreviousPath
migrate_Train_PreviousPath old =
    { position = old.position |> migrate_Coord_Coord migrate_Units_WorldUnit
    , path = old.path |> migrate_Tile_RailPath
    , reversed = old.reversed
    }


migrate_Train_Status : Evergreen.V91.Train.Status -> Evergreen.V93.Train.Status
migrate_Train_Status old =
    case old of
        Evergreen.V91.Train.WaitingAtHome ->
            Evergreen.V93.Train.WaitingAtHome

        Evergreen.V91.Train.TeleportingHome p0 ->
            Evergreen.V93.Train.TeleportingHome p0

        Evergreen.V91.Train.Travelling ->
            Evergreen.V93.Train.Travelling

        Evergreen.V91.Train.StoppedAtPostOffice p0 ->
            Evergreen.V93.Train.StoppedAtPostOffice
                { time = p0.time
                , userId = p0.userId |> migrate_Id_Id migrate_Id_UserId
                }


migrate_Train_Train : Evergreen.V91.Train.Train -> Evergreen.V93.Train.Train
migrate_Train_Train old =
    case old of
        Evergreen.V91.Train.Train p0 ->
            Evergreen.V93.Train.Train
                { position = p0.position |> migrate_Coord_Coord migrate_Units_WorldUnit
                , path = p0.path |> migrate_Tile_RailPath
                , previousPaths = p0.previousPaths |> List.map migrate_Train_PreviousPath
                , t = p0.t
                , speed = p0.speed |> migrate_Quantity_Quantity
                , home = p0.home |> migrate_Coord_Coord migrate_Units_WorldUnit
                , homePath = p0.homePath |> migrate_Tile_RailPath
                , isStuckOrDerailed = p0.isStuckOrDerailed |> migrate_Train_IsStuckOrDerailed
                , status = p0.status |> migrate_Train_Status
                , owner = p0.owner |> migrate_Id_Id migrate_Id_UserId
                , color = p0.color |> migrate_Color_Color
                }


migrate_Train_TrainDiff : Evergreen.V91.Train.TrainDiff -> Evergreen.V93.Train.TrainDiff
migrate_Train_TrainDiff old =
    case old of
        Evergreen.V91.Train.NewTrain p0 ->
            Evergreen.V93.Train.NewTrain (p0 |> migrate_Train_Train)

        Evergreen.V91.Train.TrainChanged p0 ->
            Evergreen.V93.Train.TrainChanged
                { position =
                    p0.position
                        |> migrate_Train_FieldChanged
                            (\rec ->
                                { position = rec.position |> migrate_Coord_Coord migrate_Units_WorldUnit
                                , path = rec.path |> migrate_Tile_RailPath
                                , previousPaths = rec.previousPaths |> List.map migrate_Train_PreviousPath
                                , t = rec.t
                                , speed = rec.speed |> migrate_Quantity_Quantity
                                }
                            )
                , isStuckOrDerailed = p0.isStuckOrDerailed |> migrate_Train_FieldChanged migrate_Train_IsStuckOrDerailed
                , status = p0.status |> migrate_Train_FieldChanged migrate_Train_Status
                }


migrate_Types_BackendError : Evergreen.V91.Types.BackendError -> Evergreen.V93.Types.BackendError
migrate_Types_BackendError old =
    case old of
        Evergreen.V91.Types.PostmarkError p0 p1 ->
            Evergreen.V93.Types.PostmarkError (p0 |> migrate_EmailAddress_EmailAddress) p1

        Evergreen.V91.Types.UserNotFoundWhenLoggingIn p0 ->
            Evergreen.V93.Types.UserNotFoundWhenLoggingIn (p0 |> migrate_Id_Id migrate_Id_UserId)


migrate_Types_BackendMsg : Evergreen.V91.Types.BackendMsg -> Evergreen.V93.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V91.Types.UserDisconnected p0 p1 ->
            Evergreen.V93.Types.UserDisconnected p0 p1

        Evergreen.V91.Types.UserConnected p0 p1 ->
            Evergreen.V93.Types.UserConnected p0 p1

        Evergreen.V91.Types.NotifyAdminEmailSent ->
            Evergreen.V93.Types.NotifyAdminEmailSent

        Evergreen.V91.Types.SentLoginEmail p0 p1 p2 ->
            Evergreen.V93.Types.SentLoginEmail p0 (p1 |> migrate_EmailAddress_EmailAddress) p2

        Evergreen.V91.Types.UpdateFromFrontend p0 p1 p2 p3 ->
            Evergreen.V93.Types.UpdateFromFrontend p0 p1 (p2 |> migrate_Types_ToBackend) p3

        Evergreen.V91.Types.WorldUpdateTimeElapsed p0 ->
            Evergreen.V93.Types.WorldUpdateTimeElapsed p0

        Evergreen.V91.Types.SentInviteEmail p0 p1 ->
            Evergreen.V93.Types.SentInviteEmail (p0 |> migrate_Id_SecretId migrate_Route_InviteToken)
                p1

        Evergreen.V91.Types.CheckConnectionTimeElapsed ->
            Evergreen.V93.Types.CheckConnectionTimeElapsed

        Evergreen.V91.Types.SentMailNotification p0 p1 p2 ->
            Evergreen.V93.Types.SentMailNotification p0 (p1 |> migrate_EmailAddress_EmailAddress) p2

        Evergreen.V91.Types.RegenerateCache p0 ->
            Evergreen.V93.Types.RegenerateCache p0

        Evergreen.V91.Types.SentReportVandalismAdminEmail p0 p1 p2 ->
            Evergreen.V93.Types.SentReportVandalismAdminEmail p0 (p1 |> migrate_EmailAddress_EmailAddress) p2


migrate_Types_BackendUserData : Evergreen.V91.Types.BackendUserData -> Evergreen.V93.Types.BackendUserData
migrate_Types_BackendUserData old =
    { undoHistory = old.undoHistory
    , redoHistory = old.redoHistory
    , undoCurrent = old.undoCurrent
    , mailDrafts = old.mailDrafts |> migrate_IdDict_IdDict migrate_Id_UserId (List.map migrate_MailEditor_Content)
    , cursor = old.cursor |> Maybe.map migrate_Cursor_Cursor
    , handColor = old.handColor |> migrate_Color_Colors
    , emailAddress = old.emailAddress |> migrate_EmailAddress_EmailAddress
    , acceptedInvites = old.acceptedInvites |> migrate_IdDict_IdDict migrate_Id_UserId identity
    , name = old.name |> migrate_DisplayName_DisplayName
    , allowEmailNotifications = old.allowEmailNotifications
    , timeOfDay = old.timeOfDay |> migrate_TimeOfDay_TimeOfDay
    , tileHotkeys = old.tileHotkeys |> migrate_AssocList_Dict migrate_Change_TileHotkey migrate_Tile_TileGroup
    , showNotifications = False
    , notificationsClearedAt = Effect.Time.millisToPosix 1697325179000
    }


migrate_Types_EmailResult : Evergreen.V91.Types.EmailResult -> Evergreen.V93.Types.EmailResult
migrate_Types_EmailResult old =
    case old of
        Evergreen.V91.Types.EmailSending ->
            Evergreen.V93.Types.EmailSending

        Evergreen.V91.Types.EmailSendFailed p0 ->
            Evergreen.V93.Types.EmailSendFailed p0

        Evergreen.V91.Types.EmailSent p0 ->
            Evergreen.V93.Types.EmailSent (p0 |> migrate_Postmark_PostmarkSendResponse)


migrate_Types_Invite : Evergreen.V91.Types.Invite -> Evergreen.V93.Types.Invite
migrate_Types_Invite old =
    { invitedBy = old.invitedBy |> migrate_Id_Id migrate_Id_UserId
    , invitedAt = old.invitedAt
    , invitedEmailAddress = old.invitedEmailAddress |> migrate_EmailAddress_EmailAddress
    , emailResult = old.emailResult |> migrate_Types_EmailResult
    }


migrate_Types_LoadingData_ : Evergreen.V91.Types.LoadingData_ -> Evergreen.V93.Types.LoadingData_
migrate_Types_LoadingData_ old =
    { grid = old.grid |> migrate_Grid_GridData
    , userStatus = old.userStatus |> migrate_Change_UserStatus
    , viewBounds = old.viewBounds |> migrate_Bounds_Bounds migrate_Units_CellUnit
    , trains = old.trains |> migrate_IdDict_IdDict migrate_Id_TrainId migrate_Train_Train
    , mail = old.mail |> migrate_IdDict_IdDict migrate_Id_MailId migrate_MailEditor_FrontendMail
    , cows = old.cows |> migrate_IdDict_IdDict migrate_Id_AnimalId migrate_Animal_Animal
    , cursors = old.cursors |> migrate_IdDict_IdDict migrate_Id_UserId migrate_Cursor_Cursor
    , users = old.users |> migrate_IdDict_IdDict migrate_Id_UserId migrate_User_FrontendUser
    , inviteTree = old.inviteTree |> migrate_User_InviteTree
    , isGridReadOnly = old.isGridReadOnly
    , trainsDisabled = old.trainsDisabled |> migrate_Change_AreTrainsDisabled
    }


migrate_Types_LoginRequestedBy : Evergreen.V91.Types.LoginRequestedBy -> Evergreen.V93.Types.LoginRequestedBy
migrate_Types_LoginRequestedBy old =
    case old of
        Evergreen.V91.Types.LoginRequestedByBackend ->
            Evergreen.V93.Types.LoginRequestedByBackend

        Evergreen.V91.Types.LoginRequestedByFrontend p0 ->
            Evergreen.V93.Types.LoginRequestedByFrontend p0


migrate_Types_ToBackend : Evergreen.V91.Types.ToBackend -> Evergreen.V93.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V91.Types.ConnectToBackend p0 p1 ->
            Evergreen.V93.Types.ConnectToBackend (p0 |> migrate_Bounds_Bounds migrate_Units_CellUnit)
                (p1 |> Maybe.map migrate_Route_LoginOrInviteToken)

        Evergreen.V91.Types.GridChange p0 ->
            Evergreen.V93.Types.GridChange (p0 |> migrate_List_Nonempty_Nonempty (Tuple.mapBoth (migrate_Id_Id migrate_Id_EventId) migrate_Change_LocalChange))

        Evergreen.V91.Types.ChangeViewBounds p0 ->
            Evergreen.V93.Types.PingRequest

        Evergreen.V91.Types.PingRequest ->
            Evergreen.V93.Types.PingRequest

        Evergreen.V91.Types.SendLoginEmailRequest p0 ->
            Evergreen.V93.Types.SendLoginEmailRequest (p0 |> migrate_Untrusted_Untrusted migrate_EmailAddress_EmailAddress)

        Evergreen.V91.Types.SendInviteEmailRequest p0 ->
            Evergreen.V93.Types.SendInviteEmailRequest (p0 |> migrate_Untrusted_Untrusted migrate_EmailAddress_EmailAddress)

        Evergreen.V91.Types.PostOfficePositionRequest ->
            Evergreen.V93.Types.PostOfficePositionRequest


migrate_Types_ToFrontend : Evergreen.V91.Types.ToFrontend -> Evergreen.V93.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V91.Types.LoadingData p0 ->
            Evergreen.V93.Types.LoadingData (p0 |> migrate_Types_LoadingData_)

        Evergreen.V91.Types.ChangeBroadcast p0 ->
            Evergreen.V93.Types.ChangeBroadcast (p0 |> migrate_List_Nonempty_Nonempty migrate_Change_Change)

        Evergreen.V91.Types.UnsubscribeEmailConfirmed ->
            Evergreen.V93.Types.UnsubscribeEmailConfirmed

        Evergreen.V91.Types.PingResponse p0 ->
            Evergreen.V93.Types.PingResponse p0

        Evergreen.V91.Types.SendLoginEmailResponse p0 ->
            Evergreen.V93.Types.SendLoginEmailResponse (p0 |> migrate_EmailAddress_EmailAddress)

        Evergreen.V91.Types.DebugResponse p0 ->
            Evergreen.V93.Types.DebugResponse p0

        Evergreen.V91.Types.SendInviteEmailResponse p0 ->
            Evergreen.V93.Types.SendInviteEmailResponse (p0 |> migrate_EmailAddress_EmailAddress)

        Evergreen.V91.Types.PostOfficePositionResponse p0 ->
            Evergreen.V93.Types.PostOfficePositionResponse (p0 |> Maybe.map (migrate_Coord_Coord migrate_Units_WorldUnit))

        Evergreen.V91.Types.ClientConnected ->
            Evergreen.V93.Types.ClientConnected

        Evergreen.V91.Types.CheckConnectionBroadcast ->
            Evergreen.V93.Types.CheckConnectionBroadcast


migrate_Types_ToolButton : Evergreen.V91.Types.ToolButton -> Evergreen.V93.Types.ToolButton
migrate_Types_ToolButton old =
    case old of
        Evergreen.V91.Types.HandToolButton ->
            Evergreen.V93.Types.HandToolButton

        Evergreen.V91.Types.TilePlacerToolButton p0 ->
            Evergreen.V93.Types.TilePlacerToolButton (p0 |> migrate_Tile_TileGroup)

        Evergreen.V91.Types.TilePickerToolButton ->
            Evergreen.V93.Types.TilePickerToolButton

        Evergreen.V91.Types.TextToolButton ->
            Evergreen.V93.Types.TextToolButton

        Evergreen.V91.Types.ReportToolButton ->
            Evergreen.V93.Types.ReportToolButton


migrate_Types_UiHover : Evergreen.V91.Types.UiHover -> Evergreen.V93.Types.UiHover
migrate_Types_UiHover old =
    case old of
        Evergreen.V91.Types.EmailAddressTextInputHover ->
            Evergreen.V93.Types.EmailAddressTextInputHover

        Evergreen.V91.Types.SendEmailButtonHover ->
            Evergreen.V93.Types.SendEmailButtonHover

        Evergreen.V91.Types.ToolButtonHover p0 ->
            Evergreen.V93.Types.ToolButtonHover (p0 |> migrate_Types_ToolButton)

        Evergreen.V91.Types.PrimaryColorInput ->
            Evergreen.V93.Types.PrimaryColorInput

        Evergreen.V91.Types.SecondaryColorInput ->
            Evergreen.V93.Types.SecondaryColorInput

        Evergreen.V91.Types.ShowInviteUser ->
            Evergreen.V93.Types.ShowInviteUser

        Evergreen.V91.Types.CloseInviteUser ->
            Evergreen.V93.Types.CloseInviteUser

        Evergreen.V91.Types.SubmitInviteUser ->
            Evergreen.V93.Types.SubmitInviteUser

        Evergreen.V91.Types.InviteEmailAddressTextInput ->
            Evergreen.V93.Types.InviteEmailAddressTextInput

        Evergreen.V91.Types.LowerMusicVolume ->
            Evergreen.V93.Types.LowerMusicVolume

        Evergreen.V91.Types.RaiseMusicVolume ->
            Evergreen.V93.Types.RaiseMusicVolume

        Evergreen.V91.Types.LowerSoundEffectVolume ->
            Evergreen.V93.Types.LowerSoundEffectVolume

        Evergreen.V91.Types.RaiseSoundEffectVolume ->
            Evergreen.V93.Types.RaiseSoundEffectVolume

        Evergreen.V91.Types.SettingsButton ->
            Evergreen.V93.Types.SettingsButton

        Evergreen.V91.Types.CloseSettings ->
            Evergreen.V93.Types.CloseSettings

        Evergreen.V91.Types.DisplayNameTextInput ->
            Evergreen.V93.Types.DisplayNameTextInput

        Evergreen.V91.Types.MailEditorHover p0 ->
            Evergreen.V93.Types.MailEditorHover (p0 |> migrate_MailEditor_Hover)

        Evergreen.V91.Types.YouGotMailButton ->
            Evergreen.V93.Types.YouGotMailButton

        Evergreen.V91.Types.ShowMapButton ->
            Evergreen.V93.Types.ShowMapButton

        Evergreen.V91.Types.AllowEmailNotificationsCheckbox ->
            Evergreen.V93.Types.AllowEmailNotificationsCheckbox

        Evergreen.V91.Types.UsersOnlineButton ->
            Evergreen.V93.Types.UsersOnlineButton

        Evergreen.V91.Types.CopyPositionUrlButton ->
            Evergreen.V93.Types.CopyPositionUrlButton

        Evergreen.V91.Types.ReportUserButton ->
            Evergreen.V93.Types.ReportUserButton

        Evergreen.V91.Types.ZoomInButton ->
            Evergreen.V93.Types.ZoomInButton

        Evergreen.V91.Types.ZoomOutButton ->
            Evergreen.V93.Types.ZoomOutButton

        Evergreen.V91.Types.RotateLeftButton ->
            Evergreen.V93.Types.RotateLeftButton

        Evergreen.V91.Types.RotateRightButton ->
            Evergreen.V93.Types.RotateRightButton

        Evergreen.V91.Types.AutomaticTimeOfDayButton ->
            Evergreen.V93.Types.AutomaticTimeOfDayButton

        Evergreen.V91.Types.AlwaysDayTimeOfDayButton ->
            Evergreen.V93.Types.AlwaysDayTimeOfDayButton

        Evergreen.V91.Types.AlwaysNightTimeOfDayButton ->
            Evergreen.V93.Types.AlwaysNightTimeOfDayButton

        Evergreen.V91.Types.ShowAdminPage ->
            Evergreen.V93.Types.ShowAdminPage

        Evergreen.V91.Types.AdminHover p0 ->
            Evergreen.V93.Types.AdminHover (p0 |> migrate_AdminPage_Hover)

        Evergreen.V91.Types.CategoryButton p0 ->
            Evergreen.V93.Types.CategoryButton (p0 |> migrate_Tile_Category)


migrate_Ui_BorderAndFill : Evergreen.V91.Ui.BorderAndFill -> Evergreen.V93.Ui.BorderAndFill
migrate_Ui_BorderAndFill old =
    case old of
        Evergreen.V91.Ui.NoBorderOrFill ->
            Evergreen.V93.Ui.NoBorderOrFill

        Evergreen.V91.Ui.FillOnly p0 ->
            Evergreen.V93.Ui.FillOnly (p0 |> migrate_Color_Color)

        Evergreen.V91.Ui.BorderAndFill p0 ->
            Evergreen.V93.Ui.BorderAndFill
                { borderWidth = p0.borderWidth
                , borderColor = p0.borderColor |> migrate_Color_Color
                , fillColor = p0.fillColor |> migrate_Color_Color
                }


migrate_Units_CellLocalUnit : Evergreen.V91.Units.CellLocalUnit -> Evergreen.V93.Units.CellLocalUnit
migrate_Units_CellLocalUnit old =
    case old of
        Evergreen.V91.Units.LocalUnit p0 ->
            Evergreen.V93.Units.LocalUnit p0


migrate_Units_CellUnit : Evergreen.V91.Units.CellUnit -> Evergreen.V93.Units.CellUnit
migrate_Units_CellUnit old =
    case old of
        Evergreen.V91.Units.CellUnit p0 ->
            Evergreen.V93.Units.CellUnit p0


migrate_Units_WorldUnit : Evergreen.V91.Units.WorldUnit -> Evergreen.V93.Units.WorldUnit
migrate_Units_WorldUnit old =
    case old of
        Evergreen.V91.Units.WorldUnit p0 ->
            Evergreen.V93.Units.WorldUnit p0


migrate_Untrusted_Untrusted : (a_old -> a_new) -> Evergreen.V91.Untrusted.Untrusted a_old -> Evergreen.V93.Untrusted.Untrusted a_new
migrate_Untrusted_Untrusted migrate_a old =
    case old of
        Evergreen.V91.Untrusted.Untrusted p0 ->
            Evergreen.V93.Untrusted.Untrusted (p0 |> migrate_a)


migrate_User_FrontendUser : Evergreen.V91.User.FrontendUser -> Evergreen.V93.User.FrontendUser
migrate_User_FrontendUser old =
    { name = old.name |> migrate_DisplayName_DisplayName
    , handColor = old.handColor |> migrate_Color_Colors
    }


migrate_User_InviteTree : Evergreen.V91.User.InviteTree -> Evergreen.V93.User.InviteTree
migrate_User_InviteTree old =
    case old of
        Evergreen.V91.User.InviteTree p0 ->
            Evergreen.V93.User.InviteTree
                { userId = p0.userId |> migrate_Id_Id migrate_Id_UserId
                , invited = p0.invited |> List.map migrate_User_InviteTree
                }
